Error:
  $ref: './Error.yaml'
PublicPlayer:
  $ref: './PublicPlayer.yaml'
PlayerDetail:
  $ref: './PlayerDetail.yaml'
PublicCharacter:
  $ref: './PublicCharacter.yaml'
CharacterDetail:
  $ref: './CharacterDetail.yaml'
CharacterSkill:
  $ref: './CharacterSkill.yaml'
Skill:
  $ref: './Skill.yaml'
Race:
  $ref: './Race.yaml'
Inventory:
  $ref: './Inventory.yaml'
Game:
  $ref: './Game.yaml'
Battle:
  $ref: './Battle.yaml'
GameCharacter:
  $ref: './GameCharacter.yaml'
ItemType:
  $ref: './ItemType.yaml'
EquipableType:
  $ref: './EquipableType.yaml'
DamageableType:
  $ref: './DamageableType.yaml'
ItemDamageType:
  $ref: './ItemDamageType.yaml'
