description: an inventory
type: object
additionalProperties: false
properties:
  id:
    type: string
  capacity:
    type: number
  gold:
    type: number
  weapons:
    type: array
    items:
      type: string
  armor:
    type: array
    items:
      type: string
  jewelry:
    type: array
    items:
      type: string
  spellbooks:
    type: array
    items:
      type: string
