@baseUrl = http://localhost:3000
@rnd = {{$randomInt 1000 9999}}
@bearerAuth = {{login.response.body.token}}
@player1Name = {{register1.response.body.username}}
@player1Id = {{register1.response.body.id}}
@player2Name = {{register2.response.body.username}}
@player2Id = {{register2.response.body.id}}
@gameId = {{createGame.response.body.id}}

### This file tests that players can create games, add and remove players from games,
### and delete games.  It also tests that players cannot delete games they do not own.
### TODO: It should also test that players cannot add or remove players from games they do not own.

### Create PLAYER 1
# @name register1
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "player{{rnd}}",
  "email": "player{{rnd}}@example.com",
  "password": "password"
}

### Create PLAYER 2
# @name register2
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "player{{rnd}}",
  "email": "player{{rnd}}@example.com",
  "password": "password"
}

### Login PLAYER 1
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{player1Name}}",
  "password": "password"
}

### Create a game
# @name createGame
POST {{baseUrl}}/games
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "test game {{rnd}}"
}

### Get all games
GET {{baseUrl}}/games
Authorization: Bearer {{bearerAuth}}

### Get one game
GET {{baseUrl}}/games/{{gameId}}
Authorization: Bearer {{bearerAuth}}

### Update game name
PATCH {{baseUrl}}/games/{{gameId}}
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "renamed game {{rnd}}"
}

### Delete a game
DELETE {{baseUrl}}/games/{{gameId}}
Authorization: Bearer {{bearerAuth}}

### Create a game
# @name createGame
POST {{baseUrl}}/games
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "test game {{rnd}}"
}

### Add player to a game
POST {{baseUrl}}/games/{{gameId}}/players/{{player2Id}}
Authorization: Bearer {{bearerAuth}}

### Get one game
# verify player 2 is in the game
GET {{baseUrl}}/games/{{gameId}}
Authorization: Bearer {{bearerAuth}}

### Remove player from a game
DELETE {{baseUrl}}/games/{{gameId}}/players/{{player2Id}}
Authorization: Bearer {{bearerAuth}}

### Get one game
# verify player 2 is not in the game
GET {{baseUrl}}/games/{{gameId}}
Authorization: Bearer {{bearerAuth}}

### Login PLAYER 2
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{player2Name}}",
  "password": "password"
}

### Delete a game
# verify player 2 can't delete the game
DELETE {{baseUrl}}/games/{{gameId}}
Authorization: Bearer {{bearerAuth}}



