@baseUrl = http://localhost:3000
@rnd = {{$randomInt 1000 9999}}
@bearerAuth = {{login.response.body.token}}
@player1Name = {{register1.response.body.username}}
@player1Id = {{register1.response.body.id}}
@player2Name = {{register2.response.body.username}}
@player2Id = {{register2.response.body.id}}
@gameId = {{createGame.response.body.id}}

### This file tests that if the owner of a game deletes his account,
### the game is not deleted, but the ownership is transferred to another player.

### Create PLAYER 1
# @name register1
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "player{{rnd}}",
  "email": "player{{rnd}}@example.com",
  "password": "password"
}

### Create PLAYER 2
# @name register2
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "player{{rnd}}",
  "email": "player{{rnd}}@example.com",
  "password": "password"
}

### Login PLAYER 1
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{player1Name}}",
  "password": "password"
}

### Create a game
# @name createGame
POST {{baseUrl}}/games
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "test game {{rnd}}"
}

### Add player to a game
POST {{baseUrl}}/games/{{gameId}}/players/{{player2Id}}
Authorization: Bearer {{bearerAuth}}

### Get one game
# verify player 2 is in the game
GET {{baseUrl}}/games/{{gameId}}
Authorization: Bearer {{bearerAuth}}

### Delete player 1
DELETE {{baseUrl}}/players/{{player1Id}}
Authorization: Bearer {{bearerAuth}}

### Login PLAYER 2
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{player2Name}}",
  "password": "password"
}

### Get one game
# verify player 2 is the new owner
GET {{baseUrl}}/games/{{gameId}}
Authorization: Bearer {{bearerAuth}}


