export const SpecialMoveSeed = [
  { id: 1, name: `Armor Ignore`, stamina: 30 },
  { id: 2, name: `Armor Pierce`, stamina: 30 },
  { id: 3, name: `Bleed Attack`, stamina: 30 },
  { id: 4, name: `Crushing Blow`, stamina: 20 },
  { id: 5, name: `Concussion Blow`, stamina: 20 },
  { id: 6, name: `Disarm`, stamina: 20 },
  { id: 7, name: `Dismount`, stamina: 25 },
  { id: 8, name: `Double Shot`, stamina: 35 },
  { id: 9, name: `Double Strike`, stamina: 30 },
  { id: 10, name: `Feint`, stamina: 30 },
  { id: 11, name: `Force Arrow`, stamina: 20 },
  { id: 12, name: `Scrambling Strike`, stamina: 20 },
  { id: 13, name: `Infectious Strike`, stamina: 20 },
  { id: 14, name: `Mortal Strike`, stamina: 30 },
  { id: 15, name: `Moving Shot`, stamina: 20 },
  { id: 16, name: `Mystic Arc`, stamina: 20 },
  { id: 17, name: `Nerve Strike`, stamina: 30 },
  { id: 18, name: `Paralyzing Blow`, stamina: 30 },
  { id: 19, name: `Riding Swipe`, stamina: 25 },
  { id: 20, name: `Serpent Arrow`, stamina: 25 },
  { id: 21, name: `Shadow Strike`, stamina: 20 },
  { id: 22, name: `Whirlwind Attack`, stamina: 40 }
]
