// Autogenerated 5/24/2022 11:44:46 PM
//   by GenerateServerModels. DO NOT MODIFY

export class CreateCharacterRequest {
  constructor(item: any) {
    const { name, strength, dexterity, intelligence } = item
    this.name = name
    this.strength = strength
    this.dexterity = dexterity
    this.intelligence = intelligence
  }
  name: string
  strength: number
  dexterity: number
  intelligence: number
}

export default CreateCharacterRequest
