// Autogenerated 4/5/2022 1:04:08 PM
//   by GenerateServerModels. DO NOT MODIFY
export class CreateCharacterSkillRequest {
  constructor(item: any) {
    const { skillId } = item
    this.skillId = skillId
  }
  skillId: string
}

export default CreateCharacterSkillRequest
