// Autogenerated 4/4/2022 1:26:30 AM
//   by GenerateServerModels. DO NOT MODIFY
export class UpdateCharacterSkillRequest {
  constructor(item: any) {
    const { level } = item
    this.level = level
  }
  level: number
}

export default UpdateCharacterSkillRequest
