// Autogenerated 2/25/2022 9:32:07 PM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'
import Inventory from './Inventory'
import PublicCharacter from './PublicCharacter'

/**
 * @description - Character details
 */
@Entity()
export class CharacterDetail extends PublicCharacter {
  constructor(item: any) {
    super(item)
    const { player, hp, maxHp, baseResist, inventorySize, resistPh, resistF, resistP, resistC, resistE, inventory } = item
    this.player = player
    this.hp = hp
    this.maxHp = maxHp
    this.baseResist = baseResist
    this.inventorySize = inventorySize
    this.resistPh = resistPh
    this.resistF = resistF
    this.resistP = resistP
    this.resistC = resistC
    this.resistE = resistE
    this.inventory = inventory
  }
  player: string
  hp: number
  maxHp: number
  baseResist: number
  inventorySize: number
  resistPh: number
  resistF: number
  resistP: number
  resistC: number
  resistE: number
  inventory: Inventory
}

export default CharacterDetail
