// Autogenerated 2/20/2022 11:58:42 AM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'
import PublicCharacter from './PublicCharacter'

/**
 * @description - Character details
 */
@Entity()
export class CharacterDetail extends PublicCharacter {
  constructor(item: any) {
    super(item)
    const { maxHp, baseResist, inventorySize } = item
    this.maxHp = maxHp
    this.baseResist = baseResist
    this.inventorySize = inventorySize
  }
  maxHp: number
  baseResist: number
  inventorySize: number
}

export default CharacterDetail
