// Autogenerated 4/1/2022 7:50:09 AM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'

/**
 * @description - A character's skill
 */
@Entity()
export class CharacterSkill {
  constructor(item: any) {
    const { id, name, description, level } = item
    this.id = id
    this.name = name
    this.description = description
    this.level = level
  }
  id: string
  name: string
  description: string
  level: number
}

export default CharacterSkill
