// Autogenerated 2/20/2022 11:58:42 AM
//   by GenerateServerModels. DO NOT MODIFY

/**
 * @description - Item type
 */
export enum DamageableType {
  weapon,
  armor
}

export default DamageableType
