// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY

/**
 * @description - Item type
 */
export enum DamageableType {
  weapon,
  armor
}

export default DamageableType
