// Autogenerated 2/19/2022 4:02:06 PM
import { Entity } from 'typeorm'

/**
 * description - an error
 *
 */
@Entity()
export class Error {
  constructor(item: any) {
    const { type, message } = item
    this.type = type
    this.message = message
  }
  type: string
  message: string
}

export default Error
