// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY
import { Entity } from 'typeorm'

/**
 * @description - an error
 */
@Entity()
export class Error {
  constructor(item: any) {
    const { type, message } = item
    this.type = type
    this.message = message
  }
  type: string
  message: string
}

export default Error
