// Autogenerated 2/19/2022 4:49:06 PM
import { Entity } from 'typeorm'
import Game from './Game'
import PublicCharacter from './PublicCharacter'

/**
 * @description - Game and Character
 */
@Entity()
export class GameCharacter {
  constructor(item: any) {
    const { game, character, owner } = item
    this.game = game
    this.character = character
    this.owner = owner
  }
  game: Game
  character: PublicCharacter
  owner: boolean
}

export default GameCharacter
