// Autogenerated 2/25/2022 9:02:05 PM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'

/**
 * @description - Create game object
 */
@Entity()
export class Game {
  constructor(item: any) {
    const { name, maxPlayers, id, owner } = item
    this.name = name
    this.maxPlayers = maxPlayers
    this.id = id
    this.owner = owner
  }
  name: string
  maxPlayers: number
  id: string
  owner: string
}

export default Game
