// Autogenerated 2/20/2022 11:58:42 AM
//   by GenerateServerModels. DO NOT MODIFY
import Game from './Game'
import PublicCharacter from './PublicCharacter'

/**
 * @description - Game and Character
 */
export class GameCharacter {
  constructor(item: any) {
    const { game, character, owner } = item
    this.game = game
    this.character = character
    this.owner = owner
  }
  game: Game
  character: PublicCharacter
  owner: boolean
}

export default GameCharacter
