// Autogenerated 2/19/2022 5:42:12 PM
import { Entity } from 'typeorm'

/**
 * @description - Create game object
 */
@Entity()
export class Game {
  constructor(item: any) {
    const { name, maxPlayers, id } = item
    this.name = name
    this.maxPlayers = maxPlayers
    this.id = id
  }
  name: string
  maxPlayers: number
  id: string
}

export default Game
