// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY
import { Entity } from 'typeorm'

/**
 * @description - Create game object
 */
@Entity()
export class Game {
  constructor(item: any) {
    const { name, maxPlayers, id } = item
    this.name = name
    this.maxPlayers = maxPlayers
    this.id = id
  }
  name: string
  maxPlayers: number
  id: string
}

export default Game
