// Autogenerated 2/25/2022 9:30:46 PM
//   by GenerateServerModels. DO NOT MODIFY

/**
 * @description - an inventory
 */
export class Inventory {
  constructor(item: any) {
    const { id, capacity, gold, weapons, armor, jewelry, spellbooks } = item
    this.id = id
    this.capacity = capacity
    this.gold = gold
    this.weapons = weapons
    this.armor = armor
    this.jewelry = jewelry
    this.spellbooks = spellbooks
  }
  id: string
  capacity: number
  gold: number
  weapons: string[]
  armor: string[]
  jewelry: string[]
  spellbooks: string[]
}

export default Inventory
