// Autogenerated 2/20/2022 11:58:42 AM
//   by GenerateServerModels. DO NOT MODIFY

/**
 * @description - Item damage type
 */
export enum ItemDamageType {
  damaged,
  destroyed
}

export default ItemDamageType
