// Autogenerated 2/20/2022 11:58:42 AM
//   by GenerateServerModels. DO NOT MODIFY

/**
 * @description - Item type
 */
export enum ItemType {
  weapon,
  armor,
  jewelry,
  spellbook
}

export default ItemType
