// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY

/**
 * @description - Item damage type
 */
export enum ItemDamageType {
  damaged,
  destroyed
}

export default ItemDamageType
