// Autogenerated 2/16/2022 9:08:18 PM
import { Entity } from 'typeorm'

@Entity()
export class LoginRequest {
  constructor(item: any) {
    const { email, password } = item

    this.email = email
    this.password = password
  }

  email: string
  password: string
}

export default LoginRequest
