// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY
import { Entity } from 'typeorm'
import PublicPlayer from './PublicPlayer'

/**
 * @description - Player details
 */
@Entity()
export class PlayerDetail extends PublicPlayer {
  constructor(item: any) {
    super(item)
    const { id, email } = item
    this.id = id
    this.email = email
  }
  id: string
  email: string
}

export default PlayerDetail
