// Autogenerated 2/20/2022 11:58:42 AM
//   by GenerateServerModels. DO NOT MODIFY
import PublicPlayer from './PublicPlayer'

/**
 * @description - Player details
 */
export class PlayerDetail extends PublicPlayer {
  constructor(item: any) {
    super(item)
    const { email } = item
    this.email = email
  }
  email: string
}

export default PlayerDetail
