// Autogenerated 2/19/2022 5:42:12 PM
import { Entity } from 'typeorm'

/**
 * @description - Character object
 */
@Entity()
export class PublicCharacter {
  constructor(item: any) {
    const { name, id } = item
    this.name = name
    this.id = id
  }
  name: string
  id: string
}

export default PublicCharacter
