// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY
import { Entity } from 'typeorm'

/**
 * @description - Character object
 */
@Entity()
export class PublicCharacter {
  constructor(item: any) {
    const { name, id } = item
    this.name = name
    this.id = id
  }
  name: string
  id: string
}

export default PublicCharacter
