// Autogenerated 2/19/2022 4:02:06 PM
import { Entity } from 'typeorm'

/**
 * description - Player object
 *
 */
@Entity()
export class PublicPlayer {
  constructor(item: any) {
    const { name, lastSeenAt } = item
    this.name = name
    this.lastSeenAt = lastSeenAt
  }
  name: string
  lastSeenAt: Date
}

export default PublicPlayer
