// Autogenerated 5/31/2022 4:20:59 PM
//   by GenerateServerModels. DO NOT MODIFY

import CharacterSkill from './CharacterSkill'

/**
 * @description - A race
 */
export class Race {
  constructor(item: any) {
    const { id, name, description, skills } = item
    this.id = id
    this.name = name
    this.description = description
    this.skills = skills
  }
  id: string
  name: string
  description: string
  skills: CharacterSkill[]
}

export default Race
