import { MigrationInterface, QueryRunner } from "typeorm";

export class battle1662797511967 implements MigrationInterface {
    name = 'battle1662797511967'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "battle" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "round" integer NOT NULL DEFAULT (1), "gameId" integer NOT NULL, "initiatorId" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "battle_participants_character" ("battleId" integer NOT NULL, "characterId" integer NOT NULL, PRIMARY KEY ("battleId", "characterId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_10e745f65df54dea13dd5be754" ON "battle_participants_character" ("battleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4688b0786211e3b51c5d01b6d" ON "battle_participants_character" ("characterId") `);
        await queryRunner.query(`CREATE TABLE "temporary_monster_instance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "orighp" integer NOT NULL, "hp" integer NOT NULL, "magery" integer NOT NULL, "evalInt" integer NOT NULL, "tactics" integer NOT NULL, "resistSpell" integer NOT NULL, "anatomy" integer NOT NULL, "strength" integer NOT NULL, "dexterity" integer NOT NULL, "intelligence" integer NOT NULL, "baseDmg" varchar NOT NULL, "initiative" integer NOT NULL, "tamed" boolean NOT NULL, "actionName" varchar NOT NULL, "actionValue" integer NOT NULL, "actionDescription" text NOT NULL, "actionDmgAmount" integer NOT NULL, "hoverStats" varchar NOT NULL, "specials" varchar NOT NULL, "animate" boolean NOT NULL, "counter" integer NOT NULL, "meleeDmg" integer NOT NULL, "tameName" varchar NOT NULL, "stomach" integer NOT NULL, "appetite" integer NOT NULL, "obedience" integer NOT NULL, "tracking" integer NOT NULL, "resistPh" integer NOT NULL, "resistC" integer NOT NULL, "resistE" integer NOT NULL, "resistF" integer NOT NULL, "resistP" integer NOT NULL, "ownerId" integer, "monsterId" integer NOT NULL, "nextActionId" integer, "actionDamageTypeId" integer, "battleAsEnemyId" integer, "battleAsFriendlyId" integer, CONSTRAINT "FK_2314eab436f3d09b5a7da01cba1" FOREIGN KEY ("actionDamageTypeId") REFERENCES "damage_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_b135cc5f67558d624613805f41c" FOREIGN KEY ("nextActionId") REFERENCES "monster_action" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5046593d4bafe954bfdcfa5d270" FOREIGN KEY ("ownerId") REFERENCES "character" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_d7eb15c80296ded1de6630838f7" FOREIGN KEY ("monsterId") REFERENCES "monster" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_monster_instance"("id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId") SELECT "id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId" FROM "monster_instance"`);
        await queryRunner.query(`DROP TABLE "monster_instance"`);
        await queryRunner.query(`ALTER TABLE "temporary_monster_instance" RENAME TO "monster_instance"`);
        await queryRunner.query(`CREATE TABLE "temporary_monster_instance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "orighp" integer NOT NULL, "hp" integer NOT NULL, "magery" integer NOT NULL, "evalInt" integer NOT NULL, "tactics" integer NOT NULL, "resistSpell" integer NOT NULL, "anatomy" integer NOT NULL, "strength" integer NOT NULL, "dexterity" integer NOT NULL, "intelligence" integer NOT NULL, "baseDmg" varchar NOT NULL, "initiative" integer NOT NULL, "tamed" boolean NOT NULL, "actionName" varchar NOT NULL, "actionValue" integer NOT NULL, "actionDescription" text NOT NULL, "actionDmgAmount" integer NOT NULL, "hoverStats" varchar NOT NULL, "specials" varchar NOT NULL, "animate" boolean NOT NULL, "counter" integer NOT NULL, "meleeDmg" integer NOT NULL, "tameName" varchar NOT NULL, "stomach" integer NOT NULL, "appetite" integer NOT NULL, "obedience" integer NOT NULL, "tracking" integer NOT NULL, "resistPh" integer NOT NULL, "resistC" integer NOT NULL, "resistE" integer NOT NULL, "resistF" integer NOT NULL, "resistP" integer NOT NULL, "ownerId" integer, "monsterId" integer NOT NULL, "nextActionId" integer, "actionDamageTypeId" integer, "battleAsEnemyId" integer, "battleAsFriendlyId" integer, CONSTRAINT "FK_2314eab436f3d09b5a7da01cba1" FOREIGN KEY ("actionDamageTypeId") REFERENCES "damage_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_b135cc5f67558d624613805f41c" FOREIGN KEY ("nextActionId") REFERENCES "monster_action" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5046593d4bafe954bfdcfa5d270" FOREIGN KEY ("ownerId") REFERENCES "character" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_d7eb15c80296ded1de6630838f7" FOREIGN KEY ("monsterId") REFERENCES "monster" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_53df880160c0d0d836cb41ec8af" FOREIGN KEY ("battleAsEnemyId") REFERENCES "battle" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_31dddd05e9b71ae815cb17c3be1" FOREIGN KEY ("battleAsFriendlyId") REFERENCES "battle" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_monster_instance"("id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId", "battleAsEnemyId", "battleAsFriendlyId") SELECT "id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId", "battleAsEnemyId", "battleAsFriendlyId" FROM "monster_instance"`);
        await queryRunner.query(`DROP TABLE "monster_instance"`);
        await queryRunner.query(`ALTER TABLE "temporary_monster_instance" RENAME TO "monster_instance"`);
        await queryRunner.query(`CREATE TABLE "temporary_battle" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "round" integer NOT NULL DEFAULT (1), "gameId" integer NOT NULL, "initiatorId" integer NOT NULL, CONSTRAINT "FK_dd8df503fb950a185819b9a07c7" FOREIGN KEY ("gameId") REFERENCES "game" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9ef6fcbc7ceb864da3bb731e587" FOREIGN KEY ("initiatorId") REFERENCES "character" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_battle"("id", "createdAt", "updatedAt", "round", "gameId", "initiatorId") SELECT "id", "createdAt", "updatedAt", "round", "gameId", "initiatorId" FROM "battle"`);
        await queryRunner.query(`DROP TABLE "battle"`);
        await queryRunner.query(`ALTER TABLE "temporary_battle" RENAME TO "battle"`);
        await queryRunner.query(`DROP INDEX "IDX_10e745f65df54dea13dd5be754"`);
        await queryRunner.query(`DROP INDEX "IDX_a4688b0786211e3b51c5d01b6d"`);
        await queryRunner.query(`CREATE TABLE "temporary_battle_participants_character" ("battleId" integer NOT NULL, "characterId" integer NOT NULL, CONSTRAINT "FK_10e745f65df54dea13dd5be7546" FOREIGN KEY ("battleId") REFERENCES "battle" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_a4688b0786211e3b51c5d01b6dd" FOREIGN KEY ("characterId") REFERENCES "character" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("battleId", "characterId"))`);
        await queryRunner.query(`INSERT INTO "temporary_battle_participants_character"("battleId", "characterId") SELECT "battleId", "characterId" FROM "battle_participants_character"`);
        await queryRunner.query(`DROP TABLE "battle_participants_character"`);
        await queryRunner.query(`ALTER TABLE "temporary_battle_participants_character" RENAME TO "battle_participants_character"`);
        await queryRunner.query(`CREATE INDEX "IDX_10e745f65df54dea13dd5be754" ON "battle_participants_character" ("battleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4688b0786211e3b51c5d01b6d" ON "battle_participants_character" ("characterId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_a4688b0786211e3b51c5d01b6d"`);
        await queryRunner.query(`DROP INDEX "IDX_10e745f65df54dea13dd5be754"`);
        await queryRunner.query(`ALTER TABLE "battle_participants_character" RENAME TO "temporary_battle_participants_character"`);
        await queryRunner.query(`CREATE TABLE "battle_participants_character" ("battleId" integer NOT NULL, "characterId" integer NOT NULL, PRIMARY KEY ("battleId", "characterId"))`);
        await queryRunner.query(`INSERT INTO "battle_participants_character"("battleId", "characterId") SELECT "battleId", "characterId" FROM "temporary_battle_participants_character"`);
        await queryRunner.query(`DROP TABLE "temporary_battle_participants_character"`);
        await queryRunner.query(`CREATE INDEX "IDX_a4688b0786211e3b51c5d01b6d" ON "battle_participants_character" ("characterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_10e745f65df54dea13dd5be754" ON "battle_participants_character" ("battleId") `);
        await queryRunner.query(`ALTER TABLE "battle" RENAME TO "temporary_battle"`);
        await queryRunner.query(`CREATE TABLE "battle" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "round" integer NOT NULL DEFAULT (1), "gameId" integer NOT NULL, "initiatorId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "battle"("id", "createdAt", "updatedAt", "round", "gameId", "initiatorId") SELECT "id", "createdAt", "updatedAt", "round", "gameId", "initiatorId" FROM "temporary_battle"`);
        await queryRunner.query(`DROP TABLE "temporary_battle"`);
        await queryRunner.query(`ALTER TABLE "monster_instance" RENAME TO "temporary_monster_instance"`);
        await queryRunner.query(`CREATE TABLE "monster_instance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "orighp" integer NOT NULL, "hp" integer NOT NULL, "magery" integer NOT NULL, "evalInt" integer NOT NULL, "tactics" integer NOT NULL, "resistSpell" integer NOT NULL, "anatomy" integer NOT NULL, "strength" integer NOT NULL, "dexterity" integer NOT NULL, "intelligence" integer NOT NULL, "baseDmg" varchar NOT NULL, "initiative" integer NOT NULL, "tamed" boolean NOT NULL, "actionName" varchar NOT NULL, "actionValue" integer NOT NULL, "actionDescription" text NOT NULL, "actionDmgAmount" integer NOT NULL, "hoverStats" varchar NOT NULL, "specials" varchar NOT NULL, "animate" boolean NOT NULL, "counter" integer NOT NULL, "meleeDmg" integer NOT NULL, "tameName" varchar NOT NULL, "stomach" integer NOT NULL, "appetite" integer NOT NULL, "obedience" integer NOT NULL, "tracking" integer NOT NULL, "resistPh" integer NOT NULL, "resistC" integer NOT NULL, "resistE" integer NOT NULL, "resistF" integer NOT NULL, "resistP" integer NOT NULL, "ownerId" integer, "monsterId" integer NOT NULL, "nextActionId" integer, "actionDamageTypeId" integer, "battleAsEnemyId" integer, "battleAsFriendlyId" integer, CONSTRAINT "FK_2314eab436f3d09b5a7da01cba1" FOREIGN KEY ("actionDamageTypeId") REFERENCES "damage_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_b135cc5f67558d624613805f41c" FOREIGN KEY ("nextActionId") REFERENCES "monster_action" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5046593d4bafe954bfdcfa5d270" FOREIGN KEY ("ownerId") REFERENCES "character" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_d7eb15c80296ded1de6630838f7" FOREIGN KEY ("monsterId") REFERENCES "monster" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "monster_instance"("id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId", "battleAsEnemyId", "battleAsFriendlyId") SELECT "id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId", "battleAsEnemyId", "battleAsFriendlyId" FROM "temporary_monster_instance"`);
        await queryRunner.query(`DROP TABLE "temporary_monster_instance"`);
        await queryRunner.query(`ALTER TABLE "monster_instance" RENAME TO "temporary_monster_instance"`);
        await queryRunner.query(`CREATE TABLE "monster_instance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "orighp" integer NOT NULL, "hp" integer NOT NULL, "magery" integer NOT NULL, "evalInt" integer NOT NULL, "tactics" integer NOT NULL, "resistSpell" integer NOT NULL, "anatomy" integer NOT NULL, "strength" integer NOT NULL, "dexterity" integer NOT NULL, "intelligence" integer NOT NULL, "baseDmg" varchar NOT NULL, "initiative" integer NOT NULL, "tamed" boolean NOT NULL, "actionName" varchar NOT NULL, "actionValue" integer NOT NULL, "actionDescription" text NOT NULL, "actionDmgAmount" integer NOT NULL, "hoverStats" varchar NOT NULL, "specials" varchar NOT NULL, "animate" boolean NOT NULL, "counter" integer NOT NULL, "meleeDmg" integer NOT NULL, "tameName" varchar NOT NULL, "stomach" integer NOT NULL, "appetite" integer NOT NULL, "obedience" integer NOT NULL, "tracking" integer NOT NULL, "resistPh" integer NOT NULL, "resistC" integer NOT NULL, "resistE" integer NOT NULL, "resistF" integer NOT NULL, "resistP" integer NOT NULL, "ownerId" integer, "monsterId" integer NOT NULL, "nextActionId" integer, "actionDamageTypeId" integer, CONSTRAINT "FK_2314eab436f3d09b5a7da01cba1" FOREIGN KEY ("actionDamageTypeId") REFERENCES "damage_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_b135cc5f67558d624613805f41c" FOREIGN KEY ("nextActionId") REFERENCES "monster_action" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5046593d4bafe954bfdcfa5d270" FOREIGN KEY ("ownerId") REFERENCES "character" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_d7eb15c80296ded1de6630838f7" FOREIGN KEY ("monsterId") REFERENCES "monster" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "monster_instance"("id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId") SELECT "id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId" FROM "temporary_monster_instance"`);
        await queryRunner.query(`DROP TABLE "temporary_monster_instance"`);
        await queryRunner.query(`DROP INDEX "IDX_a4688b0786211e3b51c5d01b6d"`);
        await queryRunner.query(`DROP INDEX "IDX_10e745f65df54dea13dd5be754"`);
        await queryRunner.query(`DROP TABLE "battle_participants_character"`);
        await queryRunner.query(`DROP TABLE "battle"`);
    }

}
