import { MigrationInterface, QueryRunner } from "typeorm";

export class weapons1662919910782 implements MigrationInterface {
    name = 'weapons1662919910782'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "material_type" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "material" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "weaponDurability" integer NOT NULL, "canSpawn" boolean NOT NULL, "baseMaterialId" integer)`);
        await queryRunner.query(`CREATE TABLE "weapon_skill" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "weapon_attribute" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "value" varchar NOT NULL, "hand" integer NOT NULL, "skillId" integer)`);
        await queryRunner.query(`CREATE TABLE "weapon_instance_attribute" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "value" integer NOT NULL, "weaponId" integer, "attributeId" integer NOT NULL, "slayerId" integer)`);
        await queryRunner.query(`CREATE TABLE "special_move" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "stamina" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "weapon" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "damage" varchar NOT NULL, "range" integer NOT NULL, "speed" integer NOT NULL, "strength" integer NOT NULL, "hand" integer NOT NULL, "skillId" integer, "primaryMoveId" integer, "secondaryMoveId" integer, "materialId" integer)`);
        await queryRunner.query(`CREATE TABLE "weapon_instance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "equipped" boolean NOT NULL, "damaged" boolean NOT NULL, "weaponId" integer NOT NULL, "materialId" integer NOT NULL, "inventoryId" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "temporary_material" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "weaponDurability" integer NOT NULL, "canSpawn" boolean NOT NULL, "baseMaterialId" integer, CONSTRAINT "FK_660dc44876c3ca4028c1d3cb09c" FOREIGN KEY ("baseMaterialId") REFERENCES "material_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_material"("id", "createdAt", "updatedAt", "name", "weaponDurability", "canSpawn", "baseMaterialId") SELECT "id", "createdAt", "updatedAt", "name", "weaponDurability", "canSpawn", "baseMaterialId" FROM "material"`);
        await queryRunner.query(`DROP TABLE "material"`);
        await queryRunner.query(`ALTER TABLE "temporary_material" RENAME TO "material"`);
        await queryRunner.query(`CREATE TABLE "temporary_weapon_attribute" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "value" varchar NOT NULL, "hand" integer NOT NULL, "skillId" integer, CONSTRAINT "FK_8692005a61ac760793a1f48a74e" FOREIGN KEY ("skillId") REFERENCES "weapon_skill" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_weapon_attribute"("id", "createdAt", "updatedAt", "name", "value", "hand", "skillId") SELECT "id", "createdAt", "updatedAt", "name", "value", "hand", "skillId" FROM "weapon_attribute"`);
        await queryRunner.query(`DROP TABLE "weapon_attribute"`);
        await queryRunner.query(`ALTER TABLE "temporary_weapon_attribute" RENAME TO "weapon_attribute"`);
        await queryRunner.query(`CREATE TABLE "temporary_weapon_instance_attribute" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "value" integer NOT NULL, "weaponId" integer, "attributeId" integer NOT NULL, "slayerId" integer, CONSTRAINT "FK_4b97b438fbe154834ce77980a1c" FOREIGN KEY ("weaponId") REFERENCES "weapon_instance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_a0cb161f84e0e9b678488137361" FOREIGN KEY ("attributeId") REFERENCES "weapon_attribute" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_a6d2ed8bfb085361d05ef3c7418" FOREIGN KEY ("slayerId") REFERENCES "slayer_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_weapon_instance_attribute"("id", "createdAt", "updatedAt", "value", "weaponId", "attributeId", "slayerId") SELECT "id", "createdAt", "updatedAt", "value", "weaponId", "attributeId", "slayerId" FROM "weapon_instance_attribute"`);
        await queryRunner.query(`DROP TABLE "weapon_instance_attribute"`);
        await queryRunner.query(`ALTER TABLE "temporary_weapon_instance_attribute" RENAME TO "weapon_instance_attribute"`);
        await queryRunner.query(`CREATE TABLE "temporary_weapon" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "damage" varchar NOT NULL, "range" integer NOT NULL, "speed" integer NOT NULL, "strength" integer NOT NULL, "hand" integer NOT NULL, "skillId" integer, "primaryMoveId" integer, "secondaryMoveId" integer, "materialId" integer, CONSTRAINT "FK_8be5bdcfeb89e0312f103961b82" FOREIGN KEY ("skillId") REFERENCES "weapon_skill" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_2a44d0c5e0cd7a10ada2cd92d5a" FOREIGN KEY ("primaryMoveId") REFERENCES "special_move" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7e5f0c345a7e0ffeb4b017da179" FOREIGN KEY ("secondaryMoveId") REFERENCES "special_move" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_37827972cb873b58757034e4cb8" FOREIGN KEY ("materialId") REFERENCES "material_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_weapon"("id", "createdAt", "updatedAt", "name", "damage", "range", "speed", "strength", "hand", "skillId", "primaryMoveId", "secondaryMoveId", "materialId") SELECT "id", "createdAt", "updatedAt", "name", "damage", "range", "speed", "strength", "hand", "skillId", "primaryMoveId", "secondaryMoveId", "materialId" FROM "weapon"`);
        await queryRunner.query(`DROP TABLE "weapon"`);
        await queryRunner.query(`ALTER TABLE "temporary_weapon" RENAME TO "weapon"`);
        await queryRunner.query(`CREATE TABLE "temporary_weapon_instance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "equipped" boolean NOT NULL, "damaged" boolean NOT NULL, "weaponId" integer NOT NULL, "materialId" integer NOT NULL, "inventoryId" integer NOT NULL, CONSTRAINT "FK_2bd4a3ac129497152ed4f0f0477" FOREIGN KEY ("weaponId") REFERENCES "weapon" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_18a2f0d22cbd590d163720c0c9d" FOREIGN KEY ("materialId") REFERENCES "material" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_c38c7860129c74aa09486d2b5ec" FOREIGN KEY ("inventoryId") REFERENCES "inventory" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_weapon_instance"("id", "createdAt", "updatedAt", "equipped", "damaged", "weaponId", "materialId", "inventoryId") SELECT "id", "createdAt", "updatedAt", "equipped", "damaged", "weaponId", "materialId", "inventoryId" FROM "weapon_instance"`);
        await queryRunner.query(`DROP TABLE "weapon_instance"`);
        await queryRunner.query(`ALTER TABLE "temporary_weapon_instance" RENAME TO "weapon_instance"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "weapon_instance" RENAME TO "temporary_weapon_instance"`);
        await queryRunner.query(`CREATE TABLE "weapon_instance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "equipped" boolean NOT NULL, "damaged" boolean NOT NULL, "weaponId" integer NOT NULL, "materialId" integer NOT NULL, "inventoryId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "weapon_instance"("id", "createdAt", "updatedAt", "equipped", "damaged", "weaponId", "materialId", "inventoryId") SELECT "id", "createdAt", "updatedAt", "equipped", "damaged", "weaponId", "materialId", "inventoryId" FROM "temporary_weapon_instance"`);
        await queryRunner.query(`DROP TABLE "temporary_weapon_instance"`);
        await queryRunner.query(`ALTER TABLE "weapon" RENAME TO "temporary_weapon"`);
        await queryRunner.query(`CREATE TABLE "weapon" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "damage" varchar NOT NULL, "range" integer NOT NULL, "speed" integer NOT NULL, "strength" integer NOT NULL, "hand" integer NOT NULL, "skillId" integer, "primaryMoveId" integer, "secondaryMoveId" integer, "materialId" integer)`);
        await queryRunner.query(`INSERT INTO "weapon"("id", "createdAt", "updatedAt", "name", "damage", "range", "speed", "strength", "hand", "skillId", "primaryMoveId", "secondaryMoveId", "materialId") SELECT "id", "createdAt", "updatedAt", "name", "damage", "range", "speed", "strength", "hand", "skillId", "primaryMoveId", "secondaryMoveId", "materialId" FROM "temporary_weapon"`);
        await queryRunner.query(`DROP TABLE "temporary_weapon"`);
        await queryRunner.query(`ALTER TABLE "weapon_instance_attribute" RENAME TO "temporary_weapon_instance_attribute"`);
        await queryRunner.query(`CREATE TABLE "weapon_instance_attribute" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "value" integer NOT NULL, "weaponId" integer, "attributeId" integer NOT NULL, "slayerId" integer)`);
        await queryRunner.query(`INSERT INTO "weapon_instance_attribute"("id", "createdAt", "updatedAt", "value", "weaponId", "attributeId", "slayerId") SELECT "id", "createdAt", "updatedAt", "value", "weaponId", "attributeId", "slayerId" FROM "temporary_weapon_instance_attribute"`);
        await queryRunner.query(`DROP TABLE "temporary_weapon_instance_attribute"`);
        await queryRunner.query(`ALTER TABLE "weapon_attribute" RENAME TO "temporary_weapon_attribute"`);
        await queryRunner.query(`CREATE TABLE "weapon_attribute" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "value" varchar NOT NULL, "hand" integer NOT NULL, "skillId" integer)`);
        await queryRunner.query(`INSERT INTO "weapon_attribute"("id", "createdAt", "updatedAt", "name", "value", "hand", "skillId") SELECT "id", "createdAt", "updatedAt", "name", "value", "hand", "skillId" FROM "temporary_weapon_attribute"`);
        await queryRunner.query(`DROP TABLE "temporary_weapon_attribute"`);
        await queryRunner.query(`ALTER TABLE "material" RENAME TO "temporary_material"`);
        await queryRunner.query(`CREATE TABLE "material" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "weaponDurability" integer NOT NULL, "canSpawn" boolean NOT NULL, "baseMaterialId" integer)`);
        await queryRunner.query(`INSERT INTO "material"("id", "createdAt", "updatedAt", "name", "weaponDurability", "canSpawn", "baseMaterialId") SELECT "id", "createdAt", "updatedAt", "name", "weaponDurability", "canSpawn", "baseMaterialId" FROM "temporary_material"`);
        await queryRunner.query(`DROP TABLE "temporary_material"`);
        await queryRunner.query(`DROP TABLE "weapon_instance"`);
        await queryRunner.query(`DROP TABLE "weapon"`);
        await queryRunner.query(`DROP TABLE "special_move"`);
        await queryRunner.query(`DROP TABLE "weapon_instance_attribute"`);
        await queryRunner.query(`DROP TABLE "weapon_attribute"`);
        await queryRunner.query(`DROP TABLE "weapon_skill"`);
        await queryRunner.query(`DROP TABLE "material"`);
        await queryRunner.query(`DROP TABLE "material_type"`);
    }

}
