import { MigrationInterface, QueryRunner } from "typeorm";

export class characterMonsterInventories1662921117192 implements MigrationInterface {
    name = 'characterMonsterInventories1662921117192'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_monster_instance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "orighp" integer NOT NULL, "hp" integer NOT NULL, "magery" integer NOT NULL, "evalInt" integer NOT NULL, "tactics" integer NOT NULL, "resistSpell" integer NOT NULL, "anatomy" integer NOT NULL, "strength" integer NOT NULL, "dexterity" integer NOT NULL, "intelligence" integer NOT NULL, "baseDmg" varchar NOT NULL, "initiative" integer NOT NULL, "tamed" boolean NOT NULL, "actionName" varchar NOT NULL, "actionValue" integer NOT NULL, "actionDescription" text NOT NULL, "actionDmgAmount" integer NOT NULL, "hoverStats" varchar NOT NULL, "specials" varchar NOT NULL, "animate" boolean NOT NULL, "counter" integer NOT NULL, "meleeDmg" integer NOT NULL, "tameName" varchar NOT NULL, "stomach" integer NOT NULL, "appetite" integer NOT NULL, "obedience" integer NOT NULL, "tracking" integer NOT NULL, "resistPh" integer NOT NULL, "resistC" integer NOT NULL, "resistE" integer NOT NULL, "resistF" integer NOT NULL, "resistP" integer NOT NULL, "ownerId" integer, "monsterId" integer NOT NULL, "nextActionId" integer, "actionDamageTypeId" integer, "battleAsEnemyId" integer, "battleAsFriendlyId" integer, "lootId" integer, CONSTRAINT "UQ_c8a86fc6a627c17f8fe910f832f" UNIQUE ("lootId"), CONSTRAINT "FK_31dddd05e9b71ae815cb17c3be1" FOREIGN KEY ("battleAsFriendlyId") REFERENCES "battle" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_53df880160c0d0d836cb41ec8af" FOREIGN KEY ("battleAsEnemyId") REFERENCES "battle" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_d7eb15c80296ded1de6630838f7" FOREIGN KEY ("monsterId") REFERENCES "monster" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5046593d4bafe954bfdcfa5d270" FOREIGN KEY ("ownerId") REFERENCES "character" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_b135cc5f67558d624613805f41c" FOREIGN KEY ("nextActionId") REFERENCES "monster_action" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_2314eab436f3d09b5a7da01cba1" FOREIGN KEY ("actionDamageTypeId") REFERENCES "damage_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_monster_instance"("id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId", "battleAsEnemyId", "battleAsFriendlyId") SELECT "id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId", "battleAsEnemyId", "battleAsFriendlyId" FROM "monster_instance"`);
        await queryRunner.query(`DROP TABLE "monster_instance"`);
        await queryRunner.query(`ALTER TABLE "temporary_monster_instance" RENAME TO "monster_instance"`);
        await queryRunner.query(`CREATE TABLE "temporary_character" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "hp" integer NOT NULL DEFAULT (1), "mana" integer NOT NULL DEFAULT (0), "strength" integer NOT NULL, "dexterity" integer NOT NULL, "intelligence" integer NOT NULL, "sleep" integer NOT NULL DEFAULT (1), "hunger" integer NOT NULL DEFAULT (1), "stamina" integer NOT NULL DEFAULT (1), "gameId" integer NOT NULL, "playerId" integer NOT NULL, "raceId" integer, "inventoryId" integer NOT NULL, CONSTRAINT "UQ_c2cb8e347289ab205255d160586" UNIQUE ("inventoryId"), CONSTRAINT "FK_a7485d062b19695002b6175e8fb" FOREIGN KEY ("raceId") REFERENCES "race" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_deaa8cb01bd0a343e8b649d32ce" FOREIGN KEY ("gameId") REFERENCES "game" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5b277d0c9baa952e5c9a95e59a5" FOREIGN KEY ("playerId") REFERENCES "player" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_character"("id", "createdAt", "updatedAt", "name", "hp", "mana", "strength", "dexterity", "intelligence", "sleep", "hunger", "stamina", "gameId", "playerId", "raceId") SELECT "id", "createdAt", "updatedAt", "name", "hp", "mana", "strength", "dexterity", "intelligence", "sleep", "hunger", "stamina", "gameId", "playerId", "raceId" FROM "character"`);
        await queryRunner.query(`DROP TABLE "character"`);
        await queryRunner.query(`ALTER TABLE "temporary_character" RENAME TO "character"`);
        await queryRunner.query(`CREATE TABLE "temporary_monster_instance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "orighp" integer NOT NULL, "hp" integer NOT NULL, "magery" integer NOT NULL, "evalInt" integer NOT NULL, "tactics" integer NOT NULL, "resistSpell" integer NOT NULL, "anatomy" integer NOT NULL, "strength" integer NOT NULL, "dexterity" integer NOT NULL, "intelligence" integer NOT NULL, "baseDmg" varchar NOT NULL, "initiative" integer NOT NULL, "tamed" boolean NOT NULL, "actionName" varchar NOT NULL, "actionValue" integer NOT NULL, "actionDescription" text NOT NULL, "actionDmgAmount" integer NOT NULL, "hoverStats" varchar NOT NULL, "specials" varchar NOT NULL, "animate" boolean NOT NULL, "counter" integer NOT NULL, "meleeDmg" integer NOT NULL, "tameName" varchar NOT NULL, "stomach" integer NOT NULL, "appetite" integer NOT NULL, "obedience" integer NOT NULL, "tracking" integer NOT NULL, "resistPh" integer NOT NULL, "resistC" integer NOT NULL, "resistE" integer NOT NULL, "resistF" integer NOT NULL, "resistP" integer NOT NULL, "ownerId" integer, "monsterId" integer NOT NULL, "nextActionId" integer, "actionDamageTypeId" integer, "battleAsEnemyId" integer, "battleAsFriendlyId" integer, "lootId" integer, CONSTRAINT "UQ_c8a86fc6a627c17f8fe910f832f" UNIQUE ("lootId"), CONSTRAINT "FK_31dddd05e9b71ae815cb17c3be1" FOREIGN KEY ("battleAsFriendlyId") REFERENCES "battle" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_53df880160c0d0d836cb41ec8af" FOREIGN KEY ("battleAsEnemyId") REFERENCES "battle" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_d7eb15c80296ded1de6630838f7" FOREIGN KEY ("monsterId") REFERENCES "monster" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5046593d4bafe954bfdcfa5d270" FOREIGN KEY ("ownerId") REFERENCES "character" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_b135cc5f67558d624613805f41c" FOREIGN KEY ("nextActionId") REFERENCES "monster_action" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_2314eab436f3d09b5a7da01cba1" FOREIGN KEY ("actionDamageTypeId") REFERENCES "damage_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4ca8daa3cbd0d30203c14e45ae7" FOREIGN KEY ("lootId") REFERENCES "inventory" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_monster_instance"("id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId", "battleAsEnemyId", "battleAsFriendlyId", "lootId") SELECT "id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId", "battleAsEnemyId", "battleAsFriendlyId", "lootId" FROM "monster_instance"`);
        await queryRunner.query(`DROP TABLE "monster_instance"`);
        await queryRunner.query(`ALTER TABLE "temporary_monster_instance" RENAME TO "monster_instance"`);
        await queryRunner.query(`CREATE TABLE "temporary_character" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "hp" integer NOT NULL DEFAULT (1), "mana" integer NOT NULL DEFAULT (0), "strength" integer NOT NULL, "dexterity" integer NOT NULL, "intelligence" integer NOT NULL, "sleep" integer NOT NULL DEFAULT (1), "hunger" integer NOT NULL DEFAULT (1), "stamina" integer NOT NULL DEFAULT (1), "gameId" integer NOT NULL, "playerId" integer NOT NULL, "raceId" integer, "inventoryId" integer NOT NULL, CONSTRAINT "UQ_c2cb8e347289ab205255d160586" UNIQUE ("inventoryId"), CONSTRAINT "FK_a7485d062b19695002b6175e8fb" FOREIGN KEY ("raceId") REFERENCES "race" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_deaa8cb01bd0a343e8b649d32ce" FOREIGN KEY ("gameId") REFERENCES "game" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5b277d0c9baa952e5c9a95e59a5" FOREIGN KEY ("playerId") REFERENCES "player" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_13fba937ad130d9285e0f286869" FOREIGN KEY ("inventoryId") REFERENCES "inventory" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_character"("id", "createdAt", "updatedAt", "name", "hp", "mana", "strength", "dexterity", "intelligence", "sleep", "hunger", "stamina", "gameId", "playerId", "raceId", "inventoryId") SELECT "id", "createdAt", "updatedAt", "name", "hp", "mana", "strength", "dexterity", "intelligence", "sleep", "hunger", "stamina", "gameId", "playerId", "raceId", "inventoryId" FROM "character"`);
        await queryRunner.query(`DROP TABLE "character"`);
        await queryRunner.query(`ALTER TABLE "temporary_character" RENAME TO "character"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "character" RENAME TO "temporary_character"`);
        await queryRunner.query(`CREATE TABLE "character" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "hp" integer NOT NULL DEFAULT (1), "mana" integer NOT NULL DEFAULT (0), "strength" integer NOT NULL, "dexterity" integer NOT NULL, "intelligence" integer NOT NULL, "sleep" integer NOT NULL DEFAULT (1), "hunger" integer NOT NULL DEFAULT (1), "stamina" integer NOT NULL DEFAULT (1), "gameId" integer NOT NULL, "playerId" integer NOT NULL, "raceId" integer, "inventoryId" integer NOT NULL, CONSTRAINT "UQ_c2cb8e347289ab205255d160586" UNIQUE ("inventoryId"), CONSTRAINT "FK_a7485d062b19695002b6175e8fb" FOREIGN KEY ("raceId") REFERENCES "race" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_deaa8cb01bd0a343e8b649d32ce" FOREIGN KEY ("gameId") REFERENCES "game" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5b277d0c9baa952e5c9a95e59a5" FOREIGN KEY ("playerId") REFERENCES "player" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "character"("id", "createdAt", "updatedAt", "name", "hp", "mana", "strength", "dexterity", "intelligence", "sleep", "hunger", "stamina", "gameId", "playerId", "raceId", "inventoryId") SELECT "id", "createdAt", "updatedAt", "name", "hp", "mana", "strength", "dexterity", "intelligence", "sleep", "hunger", "stamina", "gameId", "playerId", "raceId", "inventoryId" FROM "temporary_character"`);
        await queryRunner.query(`DROP TABLE "temporary_character"`);
        await queryRunner.query(`ALTER TABLE "monster_instance" RENAME TO "temporary_monster_instance"`);
        await queryRunner.query(`CREATE TABLE "monster_instance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "orighp" integer NOT NULL, "hp" integer NOT NULL, "magery" integer NOT NULL, "evalInt" integer NOT NULL, "tactics" integer NOT NULL, "resistSpell" integer NOT NULL, "anatomy" integer NOT NULL, "strength" integer NOT NULL, "dexterity" integer NOT NULL, "intelligence" integer NOT NULL, "baseDmg" varchar NOT NULL, "initiative" integer NOT NULL, "tamed" boolean NOT NULL, "actionName" varchar NOT NULL, "actionValue" integer NOT NULL, "actionDescription" text NOT NULL, "actionDmgAmount" integer NOT NULL, "hoverStats" varchar NOT NULL, "specials" varchar NOT NULL, "animate" boolean NOT NULL, "counter" integer NOT NULL, "meleeDmg" integer NOT NULL, "tameName" varchar NOT NULL, "stomach" integer NOT NULL, "appetite" integer NOT NULL, "obedience" integer NOT NULL, "tracking" integer NOT NULL, "resistPh" integer NOT NULL, "resistC" integer NOT NULL, "resistE" integer NOT NULL, "resistF" integer NOT NULL, "resistP" integer NOT NULL, "ownerId" integer, "monsterId" integer NOT NULL, "nextActionId" integer, "actionDamageTypeId" integer, "battleAsEnemyId" integer, "battleAsFriendlyId" integer, "lootId" integer, CONSTRAINT "UQ_c8a86fc6a627c17f8fe910f832f" UNIQUE ("lootId"), CONSTRAINT "FK_31dddd05e9b71ae815cb17c3be1" FOREIGN KEY ("battleAsFriendlyId") REFERENCES "battle" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_53df880160c0d0d836cb41ec8af" FOREIGN KEY ("battleAsEnemyId") REFERENCES "battle" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_d7eb15c80296ded1de6630838f7" FOREIGN KEY ("monsterId") REFERENCES "monster" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5046593d4bafe954bfdcfa5d270" FOREIGN KEY ("ownerId") REFERENCES "character" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_b135cc5f67558d624613805f41c" FOREIGN KEY ("nextActionId") REFERENCES "monster_action" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_2314eab436f3d09b5a7da01cba1" FOREIGN KEY ("actionDamageTypeId") REFERENCES "damage_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "monster_instance"("id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId", "battleAsEnemyId", "battleAsFriendlyId", "lootId") SELECT "id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId", "battleAsEnemyId", "battleAsFriendlyId", "lootId" FROM "temporary_monster_instance"`);
        await queryRunner.query(`DROP TABLE "temporary_monster_instance"`);
        await queryRunner.query(`ALTER TABLE "character" RENAME TO "temporary_character"`);
        await queryRunner.query(`CREATE TABLE "character" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "hp" integer NOT NULL DEFAULT (1), "mana" integer NOT NULL DEFAULT (0), "strength" integer NOT NULL, "dexterity" integer NOT NULL, "intelligence" integer NOT NULL, "sleep" integer NOT NULL DEFAULT (1), "hunger" integer NOT NULL DEFAULT (1), "stamina" integer NOT NULL DEFAULT (1), "gameId" integer NOT NULL, "playerId" integer NOT NULL, "raceId" integer, CONSTRAINT "FK_a7485d062b19695002b6175e8fb" FOREIGN KEY ("raceId") REFERENCES "race" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_deaa8cb01bd0a343e8b649d32ce" FOREIGN KEY ("gameId") REFERENCES "game" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5b277d0c9baa952e5c9a95e59a5" FOREIGN KEY ("playerId") REFERENCES "player" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "character"("id", "createdAt", "updatedAt", "name", "hp", "mana", "strength", "dexterity", "intelligence", "sleep", "hunger", "stamina", "gameId", "playerId", "raceId") SELECT "id", "createdAt", "updatedAt", "name", "hp", "mana", "strength", "dexterity", "intelligence", "sleep", "hunger", "stamina", "gameId", "playerId", "raceId" FROM "temporary_character"`);
        await queryRunner.query(`DROP TABLE "temporary_character"`);
        await queryRunner.query(`ALTER TABLE "monster_instance" RENAME TO "temporary_monster_instance"`);
        await queryRunner.query(`CREATE TABLE "monster_instance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "orighp" integer NOT NULL, "hp" integer NOT NULL, "magery" integer NOT NULL, "evalInt" integer NOT NULL, "tactics" integer NOT NULL, "resistSpell" integer NOT NULL, "anatomy" integer NOT NULL, "strength" integer NOT NULL, "dexterity" integer NOT NULL, "intelligence" integer NOT NULL, "baseDmg" varchar NOT NULL, "initiative" integer NOT NULL, "tamed" boolean NOT NULL, "actionName" varchar NOT NULL, "actionValue" integer NOT NULL, "actionDescription" text NOT NULL, "actionDmgAmount" integer NOT NULL, "hoverStats" varchar NOT NULL, "specials" varchar NOT NULL, "animate" boolean NOT NULL, "counter" integer NOT NULL, "meleeDmg" integer NOT NULL, "tameName" varchar NOT NULL, "stomach" integer NOT NULL, "appetite" integer NOT NULL, "obedience" integer NOT NULL, "tracking" integer NOT NULL, "resistPh" integer NOT NULL, "resistC" integer NOT NULL, "resistE" integer NOT NULL, "resistF" integer NOT NULL, "resistP" integer NOT NULL, "ownerId" integer, "monsterId" integer NOT NULL, "nextActionId" integer, "actionDamageTypeId" integer, "battleAsEnemyId" integer, "battleAsFriendlyId" integer, CONSTRAINT "FK_31dddd05e9b71ae815cb17c3be1" FOREIGN KEY ("battleAsFriendlyId") REFERENCES "battle" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_53df880160c0d0d836cb41ec8af" FOREIGN KEY ("battleAsEnemyId") REFERENCES "battle" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_d7eb15c80296ded1de6630838f7" FOREIGN KEY ("monsterId") REFERENCES "monster" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5046593d4bafe954bfdcfa5d270" FOREIGN KEY ("ownerId") REFERENCES "character" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_b135cc5f67558d624613805f41c" FOREIGN KEY ("nextActionId") REFERENCES "monster_action" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_2314eab436f3d09b5a7da01cba1" FOREIGN KEY ("actionDamageTypeId") REFERENCES "damage_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "monster_instance"("id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId", "battleAsEnemyId", "battleAsFriendlyId") SELECT "id", "createdAt", "updatedAt", "name", "orighp", "hp", "magery", "evalInt", "tactics", "resistSpell", "anatomy", "strength", "dexterity", "intelligence", "baseDmg", "initiative", "tamed", "actionName", "actionValue", "actionDescription", "actionDmgAmount", "hoverStats", "specials", "animate", "counter", "meleeDmg", "tameName", "stomach", "appetite", "obedience", "tracking", "resistPh", "resistC", "resistE", "resistF", "resistP", "ownerId", "monsterId", "nextActionId", "actionDamageTypeId", "battleAsEnemyId", "battleAsFriendlyId" FROM "temporary_monster_instance"`);
        await queryRunner.query(`DROP TABLE "temporary_monster_instance"`);
    }

}
