import { MigrationInterface, QueryRunner } from "typeorm";

export class RemoveCascading1687927775701 implements MigrationInterface {
    name = 'RemoveCascading1687927775701'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`monster_condition\` DROP FOREIGN KEY \`FK_4a316650c8248dd45d4a1e6000b\``);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` DROP FOREIGN KEY \`FK_5046593d4bafe954bfdcfa5d270\``);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` DROP FOREIGN KEY \`FK_53df880160c0d0d836cb41ec8af\``);
        await queryRunner.query(`ALTER TABLE \`battle\` DROP FOREIGN KEY \`FK_dd8df503fb950a185819b9a07c7\``);
        await queryRunner.query(`ALTER TABLE \`character_condition\` DROP FOREIGN KEY \`FK_3d1e2cd15440b6eabe9df89c891\``);
        await queryRunner.query(`ALTER TABLE \`character_skill\` DROP FOREIGN KEY \`FK_39dcbdc540ee9ff68c7e39bcbe4\``);
        await queryRunner.query(`ALTER TABLE \`character\` DROP FOREIGN KEY \`FK_5b277d0c9baa952e5c9a95e59a5\``);
        await queryRunner.query(`ALTER TABLE \`character\` DROP FOREIGN KEY \`FK_deaa8cb01bd0a343e8b649d32ce\``);
        await queryRunner.query(`ALTER TABLE \`action\` CHANGE \`value\` \`value\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_action\` DROP FOREIGN KEY \`FK_b8aad316d39b87ceb1065028cfd\``);
        await queryRunner.query(`ALTER TABLE \`monster_action\` DROP FOREIGN KEY \`FK_66e50e885cfcf9bf9155e561c94\``);
        await queryRunner.query(`ALTER TABLE \`monster_action\` CHANGE \`monsterId\` \`monsterId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_action\` CHANGE \`actionId\` \`actionId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster\` DROP FOREIGN KEY \`FK_572eb283f5e63eb6350aa93e0b8\``);
        await queryRunner.query(`ALTER TABLE \`monster\` DROP FOREIGN KEY \`FK_10fa8ba1b89415844585423dea3\``);
        await queryRunner.query(`ALTER TABLE \`monster\` CHANGE \`damageTypeId\` \`damageTypeId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster\` CHANGE \`breathDmgTypeId\` \`breathDmgTypeId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`condition\` DROP FOREIGN KEY \`FK_a9a00b82a00b60a38dde793c3cf\``);
        await queryRunner.query(`ALTER TABLE \`condition\` CHANGE \`damageTypeId\` \`damageTypeId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` DROP FOREIGN KEY \`FK_dc225a588847769fdc99bc5f51f\``);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` CHANGE \`damage\` \`damage\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` CHANGE \`targetId\` \`targetId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` CHANGE \`creatureId\` \`creatureId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`armor_class_damage_reduction\` DROP FOREIGN KEY \`FK_487d2a8f99c619b4535d2ec023b\``);
        await queryRunner.query(`ALTER TABLE \`armor_class_damage_reduction\` DROP FOREIGN KEY \`FK_55187e994e82f93943f254b1307\``);
        await queryRunner.query(`ALTER TABLE \`armor_class_damage_reduction\` CHANGE \`armorClassId\` \`armorClassId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`armor_class_damage_reduction\` CHANGE \`damageTypeId\` \`damageTypeId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`armor_class\` DROP FOREIGN KEY \`FK_c89160171695ce4026c827fac88\``);
        await queryRunner.query(`ALTER TABLE \`armor_class\` CHANGE \`reductionsId\` \`reductionsId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`armor_instance_attribute\` DROP FOREIGN KEY \`FK_a48388ff1e07be7af2710db00f4\``);
        await queryRunner.query(`ALTER TABLE \`armor_instance_attribute\` DROP FOREIGN KEY \`FK_420c5ebe6919eb0d20b4745c939\``);
        await queryRunner.query(`ALTER TABLE \`armor_instance_attribute\` CHANGE \`armorId\` \`armorId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`armor_instance_attribute\` CHANGE \`damageTypeId\` \`damageTypeId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`armor_instance_damage_reduction\` DROP FOREIGN KEY \`FK_4e8be9127052f64a93006758c9b\``);
        await queryRunner.query(`ALTER TABLE \`armor_instance_damage_reduction\` CHANGE \`armorId\` \`armorId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`armor_location\` DROP FOREIGN KEY \`FK_9b56af5a233f83408a29eaf70a3\``);
        await queryRunner.query(`ALTER TABLE \`armor_location\` CHANGE \`locationId\` \`locationId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`gem\` DROP FOREIGN KEY \`FK_da3c10c31af9c5d3660e7c9921e\``);
        await queryRunner.query(`ALTER TABLE \`gem\` DROP FOREIGN KEY \`FK_9fe3aa4b51a77e70bbbb03c03e9\``);
        await queryRunner.query(`ALTER TABLE \`gem\` CHANGE \`rarityId\` \`rarityId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`gem\` CHANGE \`categoryId\` \`categoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`skill\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`jewelry_instance_attribute\` DROP FOREIGN KEY \`FK_36bbc58501c0d06d2d40b1b39ea\``);
        await queryRunner.query(`ALTER TABLE \`jewelry_instance_attribute\` DROP FOREIGN KEY \`FK_f380f40bc89f06e782399dd3bc6\``);
        await queryRunner.query(`ALTER TABLE \`jewelry_instance_attribute\` CHANGE \`jewelryId\` \`jewelryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`jewelry_instance_attribute\` CHANGE \`skillId\` \`skillId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`jewelry_location\` DROP FOREIGN KEY \`FK_f570ea965a5b794403750333159\``);
        await queryRunner.query(`ALTER TABLE \`jewelry_location\` CHANGE \`locationId\` \`locationId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` DROP FOREIGN KEY \`FK_37761fd630309458cb283115e3c\``);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` DROP FOREIGN KEY \`FK_03e96f4108be5187f064e078ec4\``);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` DROP FOREIGN KEY \`FK_e3388e3c797c67bb2c4d790da7f\``);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` CHANGE \`skillId\` \`skillId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` CHANGE \`slayerId\` \`slayerId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` CHANGE \`spellbookId\` \`spellbookId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`material\` DROP FOREIGN KEY \`FK_660dc44876c3ca4028c1d3cb09c\``);
        await queryRunner.query(`ALTER TABLE \`material\` CHANGE \`baseMaterialId\` \`baseMaterialId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`weapon_attribute\` DROP FOREIGN KEY \`FK_8692005a61ac760793a1f48a74e\``);
        await queryRunner.query(`ALTER TABLE \`weapon_attribute\` CHANGE \`skillId\` \`skillId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`weapon_instance_attribute\` DROP FOREIGN KEY \`FK_4b97b438fbe154834ce77980a1c\``);
        await queryRunner.query(`ALTER TABLE \`weapon_instance_attribute\` DROP FOREIGN KEY \`FK_a6d2ed8bfb085361d05ef3c7418\``);
        await queryRunner.query(`ALTER TABLE \`weapon_instance_attribute\` CHANGE \`weaponId\` \`weaponId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`weapon_instance_attribute\` CHANGE \`slayerId\` \`slayerId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`weapon\` DROP FOREIGN KEY \`FK_8be5bdcfeb89e0312f103961b82\``);
        await queryRunner.query(`ALTER TABLE \`weapon\` DROP FOREIGN KEY \`FK_2a44d0c5e0cd7a10ada2cd92d5a\``);
        await queryRunner.query(`ALTER TABLE \`weapon\` DROP FOREIGN KEY \`FK_7e5f0c345a7e0ffeb4b017da179\``);
        await queryRunner.query(`ALTER TABLE \`weapon\` DROP FOREIGN KEY \`FK_37827972cb873b58757034e4cb8\``);
        await queryRunner.query(`ALTER TABLE \`weapon\` CHANGE \`skillId\` \`skillId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`weapon\` CHANGE \`primaryMoveId\` \`primaryMoveId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`weapon\` CHANGE \`secondaryMoveId\` \`secondaryMoveId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`weapon\` CHANGE \`materialId\` \`materialId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` DROP FOREIGN KEY \`FK_31dddd05e9b71ae815cb17c3be1\``);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` DROP FOREIGN KEY \`FK_b135cc5f67558d624613805f41c\``);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` DROP FOREIGN KEY \`FK_4ca8daa3cbd0d30203c14e45ae7\``);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`animate\` \`animate\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`counter\` \`counter\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`meleeDmg\` \`meleeDmg\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`tameName\` \`tameName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`battleAsEnemyId\` \`battleAsEnemyId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`battleAsFriendlyId\` \`battleAsFriendlyId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`ownerId\` \`ownerId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`nextActionId\` \`nextActionId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`lootId\` \`lootId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`player\` DROP FOREIGN KEY \`FK_a685e5d5fc1676a8bcd05e681cc\``);
        await queryRunner.query(`ALTER TABLE \`player\` CHANGE \`lastSeenAt\` \`lastSeenAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`player\` CHANGE \`currentGameId\` \`currentGameId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`character_condition\` DROP FOREIGN KEY \`FK_bf4ac274a380f50555cd37e3e41\``);
        await queryRunner.query(`ALTER TABLE \`character_condition\` CHANGE \`damage\` \`damage\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`character_condition\` CHANGE \`targetId\` \`targetId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`character_condition\` CHANGE \`characterId\` \`characterId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`race_skill\` DROP FOREIGN KEY \`FK_ef48966f9cfe3b60e02650dab48\``);
        await queryRunner.query(`ALTER TABLE \`race_skill\` DROP FOREIGN KEY \`FK_f1cee220a1c2d5975345de0ba8f\``);
        await queryRunner.query(`ALTER TABLE \`race_skill\` CHANGE \`raceId\` \`raceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`race_skill\` CHANGE \`skillId\` \`skillId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`race\` CHANGE \`hunger\` \`hunger\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`race\` CHANGE \`sleep\` \`sleep\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`character\` DROP FOREIGN KEY \`FK_a7485d062b19695002b6175e8fb\``);
        await queryRunner.query(`ALTER TABLE \`character\` DROP FOREIGN KEY \`FK_0e769efa0cc4bab7f6de8fd6554\``);
        await queryRunner.query(`ALTER TABLE \`character\` CHANGE \`raceId\` \`raceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`character\` CHANGE \`battleId\` \`battleId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`monster_action\` ADD CONSTRAINT \`FK_b8aad316d39b87ceb1065028cfd\` FOREIGN KEY (\`monsterId\`) REFERENCES \`monster\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_action\` ADD CONSTRAINT \`FK_66e50e885cfcf9bf9155e561c94\` FOREIGN KEY (\`actionId\`) REFERENCES \`action\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster\` ADD CONSTRAINT \`FK_572eb283f5e63eb6350aa93e0b8\` FOREIGN KEY (\`damageTypeId\`) REFERENCES \`damage_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster\` ADD CONSTRAINT \`FK_10fa8ba1b89415844585423dea3\` FOREIGN KEY (\`breathDmgTypeId\`) REFERENCES \`damage_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`condition\` ADD CONSTRAINT \`FK_a9a00b82a00b60a38dde793c3cf\` FOREIGN KEY (\`damageTypeId\`) REFERENCES \`damage_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` ADD CONSTRAINT \`FK_dc225a588847769fdc99bc5f51f\` FOREIGN KEY (\`targetId\`) REFERENCES \`monster_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` ADD CONSTRAINT \`FK_4a316650c8248dd45d4a1e6000b\` FOREIGN KEY (\`creatureId\`) REFERENCES \`monster_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_class_damage_reduction\` ADD CONSTRAINT \`FK_487d2a8f99c619b4535d2ec023b\` FOREIGN KEY (\`armorClassId\`) REFERENCES \`armor_class\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_class_damage_reduction\` ADD CONSTRAINT \`FK_55187e994e82f93943f254b1307\` FOREIGN KEY (\`damageTypeId\`) REFERENCES \`damage_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_class\` ADD CONSTRAINT \`FK_c89160171695ce4026c827fac88\` FOREIGN KEY (\`reductionsId\`) REFERENCES \`armor_class_damage_reduction\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_instance_attribute\` ADD CONSTRAINT \`FK_a48388ff1e07be7af2710db00f4\` FOREIGN KEY (\`armorId\`) REFERENCES \`armor_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_instance_attribute\` ADD CONSTRAINT \`FK_420c5ebe6919eb0d20b4745c939\` FOREIGN KEY (\`damageTypeId\`) REFERENCES \`damage_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_instance_damage_reduction\` ADD CONSTRAINT \`FK_4e8be9127052f64a93006758c9b\` FOREIGN KEY (\`armorId\`) REFERENCES \`armor_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_location\` ADD CONSTRAINT \`FK_9b56af5a233f83408a29eaf70a3\` FOREIGN KEY (\`locationId\`) REFERENCES \`equip_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gem\` ADD CONSTRAINT \`FK_da3c10c31af9c5d3660e7c9921e\` FOREIGN KEY (\`rarityId\`) REFERENCES \`gem_rarity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gem\` ADD CONSTRAINT \`FK_9fe3aa4b51a77e70bbbb03c03e9\` FOREIGN KEY (\`categoryId\`) REFERENCES \`item_category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`jewelry_instance_attribute\` ADD CONSTRAINT \`FK_36bbc58501c0d06d2d40b1b39ea\` FOREIGN KEY (\`jewelryId\`) REFERENCES \`jewelry_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`jewelry_instance_attribute\` ADD CONSTRAINT \`FK_f380f40bc89f06e782399dd3bc6\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`jewelry_location\` ADD CONSTRAINT \`FK_f570ea965a5b794403750333159\` FOREIGN KEY (\`locationId\`) REFERENCES \`equip_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` ADD CONSTRAINT \`FK_37761fd630309458cb283115e3c\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` ADD CONSTRAINT \`FK_03e96f4108be5187f064e078ec4\` FOREIGN KEY (\`slayerId\`) REFERENCES \`slayer_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` ADD CONSTRAINT \`FK_e3388e3c797c67bb2c4d790da7f\` FOREIGN KEY (\`spellbookId\`) REFERENCES \`spellbook_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material\` ADD CONSTRAINT \`FK_660dc44876c3ca4028c1d3cb09c\` FOREIGN KEY (\`baseMaterialId\`) REFERENCES \`material_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon_attribute\` ADD CONSTRAINT \`FK_8692005a61ac760793a1f48a74e\` FOREIGN KEY (\`skillId\`) REFERENCES \`weapon_skill\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon_instance_attribute\` ADD CONSTRAINT \`FK_4b97b438fbe154834ce77980a1c\` FOREIGN KEY (\`weaponId\`) REFERENCES \`weapon_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon_instance_attribute\` ADD CONSTRAINT \`FK_a6d2ed8bfb085361d05ef3c7418\` FOREIGN KEY (\`slayerId\`) REFERENCES \`slayer_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon\` ADD CONSTRAINT \`FK_8be5bdcfeb89e0312f103961b82\` FOREIGN KEY (\`skillId\`) REFERENCES \`weapon_skill\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon\` ADD CONSTRAINT \`FK_2a44d0c5e0cd7a10ada2cd92d5a\` FOREIGN KEY (\`primaryMoveId\`) REFERENCES \`special_move\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon\` ADD CONSTRAINT \`FK_7e5f0c345a7e0ffeb4b017da179\` FOREIGN KEY (\`secondaryMoveId\`) REFERENCES \`special_move\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon\` ADD CONSTRAINT \`FK_37827972cb873b58757034e4cb8\` FOREIGN KEY (\`materialId\`) REFERENCES \`material_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` ADD CONSTRAINT \`FK_53df880160c0d0d836cb41ec8af\` FOREIGN KEY (\`battleAsEnemyId\`) REFERENCES \`battle\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` ADD CONSTRAINT \`FK_31dddd05e9b71ae815cb17c3be1\` FOREIGN KEY (\`battleAsFriendlyId\`) REFERENCES \`battle\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` ADD CONSTRAINT \`FK_5046593d4bafe954bfdcfa5d270\` FOREIGN KEY (\`ownerId\`) REFERENCES \`character\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` ADD CONSTRAINT \`FK_b135cc5f67558d624613805f41c\` FOREIGN KEY (\`nextActionId\`) REFERENCES \`monster_action\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` ADD CONSTRAINT \`FK_4ca8daa3cbd0d30203c14e45ae7\` FOREIGN KEY (\`lootId\`) REFERENCES \`inventory\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`battle\` ADD CONSTRAINT \`FK_dd8df503fb950a185819b9a07c7\` FOREIGN KEY (\`gameId\`) REFERENCES \`game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player\` ADD CONSTRAINT \`FK_a685e5d5fc1676a8bcd05e681cc\` FOREIGN KEY (\`currentGameId\`) REFERENCES \`game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`character_condition\` ADD CONSTRAINT \`FK_bf4ac274a380f50555cd37e3e41\` FOREIGN KEY (\`targetId\`) REFERENCES \`monster_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`character_condition\` ADD CONSTRAINT \`FK_3d1e2cd15440b6eabe9df89c891\` FOREIGN KEY (\`characterId\`) REFERENCES \`character\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`race_skill\` ADD CONSTRAINT \`FK_ef48966f9cfe3b60e02650dab48\` FOREIGN KEY (\`raceId\`) REFERENCES \`race\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`race_skill\` ADD CONSTRAINT \`FK_f1cee220a1c2d5975345de0ba8f\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`character_skill\` ADD CONSTRAINT \`FK_39dcbdc540ee9ff68c7e39bcbe4\` FOREIGN KEY (\`characterId\`) REFERENCES \`character\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`character\` ADD CONSTRAINT \`FK_a7485d062b19695002b6175e8fb\` FOREIGN KEY (\`raceId\`) REFERENCES \`race\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`character\` ADD CONSTRAINT \`FK_deaa8cb01bd0a343e8b649d32ce\` FOREIGN KEY (\`gameId\`) REFERENCES \`game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`character\` ADD CONSTRAINT \`FK_5b277d0c9baa952e5c9a95e59a5\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`character\` ADD CONSTRAINT \`FK_0e769efa0cc4bab7f6de8fd6554\` FOREIGN KEY (\`battleId\`) REFERENCES \`battle\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`character\` DROP FOREIGN KEY \`FK_0e769efa0cc4bab7f6de8fd6554\``);
        await queryRunner.query(`ALTER TABLE \`character\` DROP FOREIGN KEY \`FK_5b277d0c9baa952e5c9a95e59a5\``);
        await queryRunner.query(`ALTER TABLE \`character\` DROP FOREIGN KEY \`FK_deaa8cb01bd0a343e8b649d32ce\``);
        await queryRunner.query(`ALTER TABLE \`character\` DROP FOREIGN KEY \`FK_a7485d062b19695002b6175e8fb\``);
        await queryRunner.query(`ALTER TABLE \`character_skill\` DROP FOREIGN KEY \`FK_39dcbdc540ee9ff68c7e39bcbe4\``);
        await queryRunner.query(`ALTER TABLE \`race_skill\` DROP FOREIGN KEY \`FK_f1cee220a1c2d5975345de0ba8f\``);
        await queryRunner.query(`ALTER TABLE \`race_skill\` DROP FOREIGN KEY \`FK_ef48966f9cfe3b60e02650dab48\``);
        await queryRunner.query(`ALTER TABLE \`character_condition\` DROP FOREIGN KEY \`FK_3d1e2cd15440b6eabe9df89c891\``);
        await queryRunner.query(`ALTER TABLE \`character_condition\` DROP FOREIGN KEY \`FK_bf4ac274a380f50555cd37e3e41\``);
        await queryRunner.query(`ALTER TABLE \`player\` DROP FOREIGN KEY \`FK_a685e5d5fc1676a8bcd05e681cc\``);
        await queryRunner.query(`ALTER TABLE \`battle\` DROP FOREIGN KEY \`FK_dd8df503fb950a185819b9a07c7\``);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` DROP FOREIGN KEY \`FK_4ca8daa3cbd0d30203c14e45ae7\``);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` DROP FOREIGN KEY \`FK_b135cc5f67558d624613805f41c\``);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` DROP FOREIGN KEY \`FK_5046593d4bafe954bfdcfa5d270\``);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` DROP FOREIGN KEY \`FK_31dddd05e9b71ae815cb17c3be1\``);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` DROP FOREIGN KEY \`FK_53df880160c0d0d836cb41ec8af\``);
        await queryRunner.query(`ALTER TABLE \`weapon\` DROP FOREIGN KEY \`FK_37827972cb873b58757034e4cb8\``);
        await queryRunner.query(`ALTER TABLE \`weapon\` DROP FOREIGN KEY \`FK_7e5f0c345a7e0ffeb4b017da179\``);
        await queryRunner.query(`ALTER TABLE \`weapon\` DROP FOREIGN KEY \`FK_2a44d0c5e0cd7a10ada2cd92d5a\``);
        await queryRunner.query(`ALTER TABLE \`weapon\` DROP FOREIGN KEY \`FK_8be5bdcfeb89e0312f103961b82\``);
        await queryRunner.query(`ALTER TABLE \`weapon_instance_attribute\` DROP FOREIGN KEY \`FK_a6d2ed8bfb085361d05ef3c7418\``);
        await queryRunner.query(`ALTER TABLE \`weapon_instance_attribute\` DROP FOREIGN KEY \`FK_4b97b438fbe154834ce77980a1c\``);
        await queryRunner.query(`ALTER TABLE \`weapon_attribute\` DROP FOREIGN KEY \`FK_8692005a61ac760793a1f48a74e\``);
        await queryRunner.query(`ALTER TABLE \`material\` DROP FOREIGN KEY \`FK_660dc44876c3ca4028c1d3cb09c\``);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` DROP FOREIGN KEY \`FK_e3388e3c797c67bb2c4d790da7f\``);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` DROP FOREIGN KEY \`FK_03e96f4108be5187f064e078ec4\``);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` DROP FOREIGN KEY \`FK_37761fd630309458cb283115e3c\``);
        await queryRunner.query(`ALTER TABLE \`jewelry_location\` DROP FOREIGN KEY \`FK_f570ea965a5b794403750333159\``);
        await queryRunner.query(`ALTER TABLE \`jewelry_instance_attribute\` DROP FOREIGN KEY \`FK_f380f40bc89f06e782399dd3bc6\``);
        await queryRunner.query(`ALTER TABLE \`jewelry_instance_attribute\` DROP FOREIGN KEY \`FK_36bbc58501c0d06d2d40b1b39ea\``);
        await queryRunner.query(`ALTER TABLE \`gem\` DROP FOREIGN KEY \`FK_9fe3aa4b51a77e70bbbb03c03e9\``);
        await queryRunner.query(`ALTER TABLE \`gem\` DROP FOREIGN KEY \`FK_da3c10c31af9c5d3660e7c9921e\``);
        await queryRunner.query(`ALTER TABLE \`armor_location\` DROP FOREIGN KEY \`FK_9b56af5a233f83408a29eaf70a3\``);
        await queryRunner.query(`ALTER TABLE \`armor_instance_damage_reduction\` DROP FOREIGN KEY \`FK_4e8be9127052f64a93006758c9b\``);
        await queryRunner.query(`ALTER TABLE \`armor_instance_attribute\` DROP FOREIGN KEY \`FK_420c5ebe6919eb0d20b4745c939\``);
        await queryRunner.query(`ALTER TABLE \`armor_instance_attribute\` DROP FOREIGN KEY \`FK_a48388ff1e07be7af2710db00f4\``);
        await queryRunner.query(`ALTER TABLE \`armor_class\` DROP FOREIGN KEY \`FK_c89160171695ce4026c827fac88\``);
        await queryRunner.query(`ALTER TABLE \`armor_class_damage_reduction\` DROP FOREIGN KEY \`FK_55187e994e82f93943f254b1307\``);
        await queryRunner.query(`ALTER TABLE \`armor_class_damage_reduction\` DROP FOREIGN KEY \`FK_487d2a8f99c619b4535d2ec023b\``);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` DROP FOREIGN KEY \`FK_4a316650c8248dd45d4a1e6000b\``);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` DROP FOREIGN KEY \`FK_dc225a588847769fdc99bc5f51f\``);
        await queryRunner.query(`ALTER TABLE \`condition\` DROP FOREIGN KEY \`FK_a9a00b82a00b60a38dde793c3cf\``);
        await queryRunner.query(`ALTER TABLE \`monster\` DROP FOREIGN KEY \`FK_10fa8ba1b89415844585423dea3\``);
        await queryRunner.query(`ALTER TABLE \`monster\` DROP FOREIGN KEY \`FK_572eb283f5e63eb6350aa93e0b8\``);
        await queryRunner.query(`ALTER TABLE \`monster_action\` DROP FOREIGN KEY \`FK_66e50e885cfcf9bf9155e561c94\``);
        await queryRunner.query(`ALTER TABLE \`monster_action\` DROP FOREIGN KEY \`FK_b8aad316d39b87ceb1065028cfd\``);
        await queryRunner.query(`ALTER TABLE \`character\` CHANGE \`battleId\` \`battleId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`character\` CHANGE \`raceId\` \`raceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`character\` ADD CONSTRAINT \`FK_0e769efa0cc4bab7f6de8fd6554\` FOREIGN KEY (\`battleId\`) REFERENCES \`battle\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`character\` ADD CONSTRAINT \`FK_a7485d062b19695002b6175e8fb\` FOREIGN KEY (\`raceId\`) REFERENCES \`race\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`race\` CHANGE \`sleep\` \`sleep\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`race\` CHANGE \`hunger\` \`hunger\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`race_skill\` CHANGE \`skillId\` \`skillId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`race_skill\` CHANGE \`raceId\` \`raceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`race_skill\` ADD CONSTRAINT \`FK_f1cee220a1c2d5975345de0ba8f\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`race_skill\` ADD CONSTRAINT \`FK_ef48966f9cfe3b60e02650dab48\` FOREIGN KEY (\`raceId\`) REFERENCES \`race\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`character_condition\` CHANGE \`characterId\` \`characterId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`character_condition\` CHANGE \`targetId\` \`targetId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`character_condition\` CHANGE \`damage\` \`damage\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`character_condition\` ADD CONSTRAINT \`FK_bf4ac274a380f50555cd37e3e41\` FOREIGN KEY (\`targetId\`) REFERENCES \`monster_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player\` CHANGE \`currentGameId\` \`currentGameId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`player\` CHANGE \`lastSeenAt\` \`lastSeenAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`player\` ADD CONSTRAINT \`FK_a685e5d5fc1676a8bcd05e681cc\` FOREIGN KEY (\`currentGameId\`) REFERENCES \`game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`lootId\` \`lootId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`nextActionId\` \`nextActionId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`ownerId\` \`ownerId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`battleAsFriendlyId\` \`battleAsFriendlyId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`battleAsEnemyId\` \`battleAsEnemyId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`tameName\` \`tameName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`meleeDmg\` \`meleeDmg\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`counter\` \`counter\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` CHANGE \`animate\` \`animate\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` ADD CONSTRAINT \`FK_4ca8daa3cbd0d30203c14e45ae7\` FOREIGN KEY (\`lootId\`) REFERENCES \`inventory\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` ADD CONSTRAINT \`FK_b135cc5f67558d624613805f41c\` FOREIGN KEY (\`nextActionId\`) REFERENCES \`monster_action\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` ADD CONSTRAINT \`FK_31dddd05e9b71ae815cb17c3be1\` FOREIGN KEY (\`battleAsFriendlyId\`) REFERENCES \`battle\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon\` CHANGE \`materialId\` \`materialId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`weapon\` CHANGE \`secondaryMoveId\` \`secondaryMoveId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`weapon\` CHANGE \`primaryMoveId\` \`primaryMoveId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`weapon\` CHANGE \`skillId\` \`skillId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`weapon\` ADD CONSTRAINT \`FK_37827972cb873b58757034e4cb8\` FOREIGN KEY (\`materialId\`) REFERENCES \`material_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon\` ADD CONSTRAINT \`FK_7e5f0c345a7e0ffeb4b017da179\` FOREIGN KEY (\`secondaryMoveId\`) REFERENCES \`special_move\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon\` ADD CONSTRAINT \`FK_2a44d0c5e0cd7a10ada2cd92d5a\` FOREIGN KEY (\`primaryMoveId\`) REFERENCES \`special_move\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon\` ADD CONSTRAINT \`FK_8be5bdcfeb89e0312f103961b82\` FOREIGN KEY (\`skillId\`) REFERENCES \`weapon_skill\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon_instance_attribute\` CHANGE \`slayerId\` \`slayerId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`weapon_instance_attribute\` CHANGE \`weaponId\` \`weaponId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`weapon_instance_attribute\` ADD CONSTRAINT \`FK_a6d2ed8bfb085361d05ef3c7418\` FOREIGN KEY (\`slayerId\`) REFERENCES \`slayer_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon_instance_attribute\` ADD CONSTRAINT \`FK_4b97b438fbe154834ce77980a1c\` FOREIGN KEY (\`weaponId\`) REFERENCES \`weapon_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`weapon_attribute\` CHANGE \`skillId\` \`skillId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`weapon_attribute\` ADD CONSTRAINT \`FK_8692005a61ac760793a1f48a74e\` FOREIGN KEY (\`skillId\`) REFERENCES \`weapon_skill\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material\` CHANGE \`baseMaterialId\` \`baseMaterialId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material\` ADD CONSTRAINT \`FK_660dc44876c3ca4028c1d3cb09c\` FOREIGN KEY (\`baseMaterialId\`) REFERENCES \`material_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` CHANGE \`spellbookId\` \`spellbookId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` CHANGE \`slayerId\` \`slayerId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` CHANGE \`skillId\` \`skillId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` ADD CONSTRAINT \`FK_e3388e3c797c67bb2c4d790da7f\` FOREIGN KEY (\`spellbookId\`) REFERENCES \`spellbook_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` ADD CONSTRAINT \`FK_03e96f4108be5187f064e078ec4\` FOREIGN KEY (\`slayerId\`) REFERENCES \`slayer_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spellbook_instance_attribute\` ADD CONSTRAINT \`FK_37761fd630309458cb283115e3c\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`jewelry_location\` CHANGE \`locationId\` \`locationId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`jewelry_location\` ADD CONSTRAINT \`FK_f570ea965a5b794403750333159\` FOREIGN KEY (\`locationId\`) REFERENCES \`equip_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`jewelry_instance_attribute\` CHANGE \`skillId\` \`skillId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`jewelry_instance_attribute\` CHANGE \`jewelryId\` \`jewelryId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`jewelry_instance_attribute\` ADD CONSTRAINT \`FK_f380f40bc89f06e782399dd3bc6\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`jewelry_instance_attribute\` ADD CONSTRAINT \`FK_36bbc58501c0d06d2d40b1b39ea\` FOREIGN KEY (\`jewelryId\`) REFERENCES \`jewelry_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`skill\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`gem\` CHANGE \`categoryId\` \`categoryId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`gem\` CHANGE \`rarityId\` \`rarityId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`gem\` ADD CONSTRAINT \`FK_9fe3aa4b51a77e70bbbb03c03e9\` FOREIGN KEY (\`categoryId\`) REFERENCES \`item_category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gem\` ADD CONSTRAINT \`FK_da3c10c31af9c5d3660e7c9921e\` FOREIGN KEY (\`rarityId\`) REFERENCES \`gem_rarity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_location\` CHANGE \`locationId\` \`locationId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`armor_location\` ADD CONSTRAINT \`FK_9b56af5a233f83408a29eaf70a3\` FOREIGN KEY (\`locationId\`) REFERENCES \`equip_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_instance_damage_reduction\` CHANGE \`armorId\` \`armorId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`armor_instance_damage_reduction\` ADD CONSTRAINT \`FK_4e8be9127052f64a93006758c9b\` FOREIGN KEY (\`armorId\`) REFERENCES \`armor_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_instance_attribute\` CHANGE \`damageTypeId\` \`damageTypeId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`armor_instance_attribute\` CHANGE \`armorId\` \`armorId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`armor_instance_attribute\` ADD CONSTRAINT \`FK_420c5ebe6919eb0d20b4745c939\` FOREIGN KEY (\`damageTypeId\`) REFERENCES \`damage_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_instance_attribute\` ADD CONSTRAINT \`FK_a48388ff1e07be7af2710db00f4\` FOREIGN KEY (\`armorId\`) REFERENCES \`armor_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_class\` CHANGE \`reductionsId\` \`reductionsId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`armor_class\` ADD CONSTRAINT \`FK_c89160171695ce4026c827fac88\` FOREIGN KEY (\`reductionsId\`) REFERENCES \`armor_class_damage_reduction\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_class_damage_reduction\` CHANGE \`damageTypeId\` \`damageTypeId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`armor_class_damage_reduction\` CHANGE \`armorClassId\` \`armorClassId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`armor_class_damage_reduction\` ADD CONSTRAINT \`FK_55187e994e82f93943f254b1307\` FOREIGN KEY (\`damageTypeId\`) REFERENCES \`damage_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`armor_class_damage_reduction\` ADD CONSTRAINT \`FK_487d2a8f99c619b4535d2ec023b\` FOREIGN KEY (\`armorClassId\`) REFERENCES \`armor_class\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` CHANGE \`creatureId\` \`creatureId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` CHANGE \`targetId\` \`targetId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` CHANGE \`damage\` \`damage\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` ADD CONSTRAINT \`FK_dc225a588847769fdc99bc5f51f\` FOREIGN KEY (\`targetId\`) REFERENCES \`monster_instance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`condition\` CHANGE \`damageTypeId\` \`damageTypeId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`condition\` ADD CONSTRAINT \`FK_a9a00b82a00b60a38dde793c3cf\` FOREIGN KEY (\`damageTypeId\`) REFERENCES \`damage_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster\` CHANGE \`breathDmgTypeId\` \`breathDmgTypeId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster\` CHANGE \`damageTypeId\` \`damageTypeId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster\` ADD CONSTRAINT \`FK_10fa8ba1b89415844585423dea3\` FOREIGN KEY (\`breathDmgTypeId\`) REFERENCES \`damage_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster\` ADD CONSTRAINT \`FK_572eb283f5e63eb6350aa93e0b8\` FOREIGN KEY (\`damageTypeId\`) REFERENCES \`damage_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_action\` CHANGE \`actionId\` \`actionId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_action\` CHANGE \`monsterId\` \`monsterId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`monster_action\` ADD CONSTRAINT \`FK_66e50e885cfcf9bf9155e561c94\` FOREIGN KEY (\`actionId\`) REFERENCES \`action\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_action\` ADD CONSTRAINT \`FK_b8aad316d39b87ceb1065028cfd\` FOREIGN KEY (\`monsterId\`) REFERENCES \`monster\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` CHANGE \`value\` \`value\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`character\` ADD CONSTRAINT \`FK_deaa8cb01bd0a343e8b649d32ce\` FOREIGN KEY (\`gameId\`) REFERENCES \`game\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`character\` ADD CONSTRAINT \`FK_5b277d0c9baa952e5c9a95e59a5\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`character_skill\` ADD CONSTRAINT \`FK_39dcbdc540ee9ff68c7e39bcbe4\` FOREIGN KEY (\`characterId\`) REFERENCES \`character\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`character_condition\` ADD CONSTRAINT \`FK_3d1e2cd15440b6eabe9df89c891\` FOREIGN KEY (\`characterId\`) REFERENCES \`character\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`battle\` ADD CONSTRAINT \`FK_dd8df503fb950a185819b9a07c7\` FOREIGN KEY (\`gameId\`) REFERENCES \`game\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` ADD CONSTRAINT \`FK_53df880160c0d0d836cb41ec8af\` FOREIGN KEY (\`battleAsEnemyId\`) REFERENCES \`battle\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_instance\` ADD CONSTRAINT \`FK_5046593d4bafe954bfdcfa5d270\` FOREIGN KEY (\`ownerId\`) REFERENCES \`character\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`monster_condition\` ADD CONSTRAINT \`FK_4a316650c8248dd45d4a1e6000b\` FOREIGN KEY (\`creatureId\`) REFERENCES \`monster_instance\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
