parameters:
  - name: gameId
    required: true
    in: path
    description: the gameId of the battle to retrieve
    schema:
      type: number
  - name: battleId
    required: true
    in: path
    description: the battle to retrieve
    schema:
      type: number
get:
  summary: retrieve a battle
  tags:
    - battle
  operationId: getBattle
  responses:
    200:
      $ref: '../responses/_index.yaml'#/Battle'
    404:
      $ref: '../responses/_index.yaml'#/Fail'
    500:
      $ref: '../responses/_index.yaml'#/Fail'
delete:
  summary: delete a battle
  tags:
    - battle
  operationId: deleteBattle
  responses:
    204:
      $ref: '../responses/_index.yaml'#/DeleteOrUpdate'
    404:
      $ref: '../responses/_index.yaml'#/Fail'
    500:
      $ref: '../responses/_index.yaml'#/Fail'
