parameters:
  - name: characterId
    required: true
    in: path
    description: the characterId
    schema:
      type: string
get:
  summary: retrieve character
  description: retrieves either the public character or detail, depending on the player making the request
  tags:
    - character
  operationId: getCharacterDetail
  responses:
    200:
      $ref: '../responses/_index.yaml#/CharacterDetail'
    401:
      $ref: '../responses/_index.yaml#/Fail'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
