parameters:
  - name: gameId
    required: true
    in: path
    description: the gameId
    schema:
      type: string
post:
  summary: create character
  tags:
    - character
    - game
  operationId: createCharacter
  requestBody:
    $ref: '../requests/_index.yaml#/CreateCharacter'
  responses:
    201:
      $ref: '../responses/_index.yaml#/Location'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
get:
  summary: get all characters for game
  tags:
    - character
    - game
  operationId: getGameCharacters
  responses:
    200:
      $ref: '../responses/_index.yaml#/IdCollection'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
