parameters:
  - name: characterId
    required: true
    in: path
    description: the character to modify
    schema:
      type: string
  - name: skillId
    required: true
    in: path
    description: the skill id
    schema:
      type: string
patch:
  summary: update the skill level
  operationId: updateCharacterSkill
  tags:
    - character
  requestBody:
    $ref: '../requests/_index.yaml#/UpdateCharacterSkill'
  responses:
    204:
      $ref: '../responses/_index.yaml#/DeleteOrUpdate'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
delete:
  summary: remove a skill from a character
  tags:
    - character
  operationId: deleteCharacterSkill
  responses:
    204:
      $ref: '../responses/_index.yaml#/DeleteOrUpdate'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
