post:
  summary: create a new game
  tags:
    - game
  operationId: createGame
  requestBody:
    $ref: '../requests/_index.yaml#/CreateGame'
  responses:
    201:
      $ref: '../responses/_index.yaml#/Location'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
