parameters:
  - name: playerId
    required: true
    in: path
    description: The player id to retrieve
    schema:
      type: string
get:
  summary: retrieve a player
  description: returns public info for player
  tags:
    - player
  operationId: getPlayer
  responses:
    200:
      $ref: '../responses/_index.yaml#/Player'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
