get:
  summary: get all available skills
  tags:
    - lists
  operationId: getSkills
  responses:
    200:
      $ref: '../responses/_index.yaml#/Skills'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
