// Autogenerated 4/1/2022 7:50:09 AM
//   by GenerateServerModels. DO NOT MODIFY

/**
 * @description - Battle object
 */
export class Battle {
  constructor(item: any) {
    const { id, displayName } = item
    this.id = id
    this.displayName = displayName
  }
  id: string
  displayName: string
}

export default Battle
