// Autogenerated 5/24/2022 11:47:56 PM
//   by GenerateServerModels. DO NOT MODIFY

import Inventory from './Inventory'
import PublicCharacter from './PublicCharacter'
import CharacterSkill from '../dto/CharacterSkill'

/**
 * @description - Character details
 */
export class CharacterDetail extends PublicCharacter {
  constructor(item: any) {
    super(item)
    const {
      player,
      hp,
      maxHp,
      hpReplenish,
      mana,
      maxMana,
      manaReplenish,
      strength,
      dexterity,
      intelligence,
      stamina,
      maxStamina,
      staminaReplenish,
      hunger,
      sleep,
      movement,
      hitChance,
      defChance,
      parry,
      swingSpeed,
      castSpeed,
      healSpeed,
      inventorySize,
      resistPh,
      resistF,
      resistP,
      resistC,
      resistE,
      inventory,
      raceName,
      raceDescription,
      raceSkills,
      skills
    } = item
    this.player = player
    this.hp = hp
    this.maxHp = maxHp
    this.hpReplenish = hpReplenish
    this.mana = mana
    this.maxMana = maxMana
    this.manaReplenish = manaReplenish
    this.strength = strength
    this.dexterity = dexterity
    this.intelligence = intelligence
    this.stamina = stamina
    this.maxStamina = maxStamina
    this.staminaReplenish = staminaReplenish
    this.hunger = hunger
    this.sleep = sleep
    this.movement = movement
    this.hitChance = hitChance
    this.defChance = defChance
    this.parry = parry
    this.swingSpeed = swingSpeed
    this.castSpeed = castSpeed
    this.healSpeed = healSpeed
    this.inventorySize = inventorySize
    this.resistPh = resistPh
    this.resistF = resistF
    this.resistP = resistP
    this.resistC = resistC
    this.resistE = resistE
    this.inventory = inventory
    this.raceName = raceName
    this.raceDescription = raceDescription
    this.raceSkills = raceSkills
    this.skills = skills
  }
  player: string
  hp: number
  maxHp: number
  hpReplenish: number
  mana: number
  maxMana: number
  manaReplenish: number
  strength: number
  dexterity: number
  intelligence: number
  stamina: number
  maxStamina: number
  staminaReplenish: number
  hunger: number
  sleep: number
  movement: string
  hitChance: number
  defChance: number
  parry: number
  swingSpeed: number
  castSpeed: number
  healSpeed: number
  inventorySize: number
  resistPh: number
  resistF: number
  resistP: number
  resistC: number
  resistE: number
  inventory: Inventory
  raceName: string
  raceDescription: string
  raceSkills: CharacterSkill[]
  skills: CharacterSkill[]
}

export default CharacterDetail
