// Autogenerated 2/25/2022 9:02:05 PM
//   by GenerateServerModels. DO NOT MODIFY
import User from '../models/User'

/**
 * @description - Create game object
 */
export class Game {
  constructor(item: { name: string; maxPlayers: number; id: string | number; owner: string | User }) {
    const { name, maxPlayers, id, owner } = item
    this.name = name
    this.maxPlayers = maxPlayers
    this.id = id.toString()
    if ((owner as User).id) {
      this.owner = (owner as User).id
    } else {
      this.owner = owner.toString()
    }
  }
  name: string
  maxPlayers: number
  id: string
  owner: string | number
}

export default Game
