// Autogenerated 4/3/2022 12:48:19 PM
//   by GenerateServerModels. DO NOT MODIFY

/**
 * @description - Character object
 */
export class PublicCharacter {
  constructor(item: any) {
    const { name, id } = item
    this.name = name
    this.id = id
  }
  name: string
  id: string
}

export default PublicCharacter
