// Autogenerated 2/25/2022 10:59:19 PM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'

/**
 * @description - the battle
 */
@Entity()
export class BattleResponse {
  constructor(item: any) {
    const { id, displayName } = item
    this.id = id
    this.displayName = displayName
  }
  id: string
  displayName: string
}

export default BattleResponse
