// Autogenerated 2/19/2022 4:02:06 PM
import { Entity } from 'typeorm'

/**
 * description - the battle
 *
 */
@Entity()
export class BattleResponse {
  constructor(item: any) {
  }
}

export default BattleResponse
