// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY
import { Entity } from 'typeorm'

/**
 * @description - the battle
 */
@Entity()
export class BattleResponse {
  constructor(item: any) {
  }
}

export default BattleResponse
