// Autogenerated 2/20/2022 12:12:09 PM
//   by GenerateServerModels. DO NOT MODIFY
import CharacterDetail from '../CharacterDetail'
import Character from '../../models/Character'

/**
 * @description - character response
 */
export class CharacterDetailResponse extends CharacterDetail {
  constructor(item: Character) {
    super(item)
  }
}

export default CharacterDetailResponse
