// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY
import { Entity } from 'typeorm'
import PublicCharacter from '../PublicCharacter'

/**
 * @description - character response
 */
@Entity()
export class CharacterResponse extends PublicCharacter {
  constructor(item: any) {
    super(item)
  }
}

export default CharacterResponse
