// Autogenerated 2/20/2022 12:12:09 PM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'
import CharacterDetail from '../CharacterDetail'

/**
 * @description - character response
 */
@Entity()
export class CharacterDetailResponse extends CharacterDetail {
  constructor(item: any) {
    super(item)
  }
}

export default CharacterDetailResponse
