// Autogenerated 2/20/2022 12:12:09 PM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'
import PublicCharacter from '../PublicCharacter'

/**
 * @description - character response
 */
@Entity()
export class CharacterResponse extends PublicCharacter {
  constructor(item: any) {
    super(item)
  }
}

export default CharacterResponse
