// Autogenerated 2/20/2022 12:12:09 PM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'
import Error from '../Error'

/**
 * @description - request failure
 */
@Entity()
export class FailResponse {
  constructor(item: any) {
    const { success, error } = item
    this.success = success
    this.error = error
  }
  success: boolean
  error: Error
}

export default FailResponse
