// Autogenerated 2/19/2022 4:49:06 PM
import { Entity } from 'typeorm'
import Error from '../Error'

/**
 * @description - request failure
 */
@Entity()
export class FailResponse {
  constructor(item: any) {
    const { success, error } = item
    this.success = success
    this.error = error
  }
  success: boolean
  error: Error
}

export default FailResponse
