// Autogenerated 2/23/2022 9:57:15 PM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'
import Game from '../Game'

/**
 * @description - game response
 */
@Entity()
export class GameResponse extends Game {
  constructor(item: any) {
    super(item)
  }
}

export default GameResponse
