// Autogenerated 2/19/2022 4:02:06 PM
import { Entity } from 'typeorm'

/**
 * description - collection of games
 *
 */
@Entity()
export class GamesResponse {
  constructor(item: any) {
  }
}

export default GamesResponse
