// Autogenerated 2/20/2022 12:12:09 PM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'
import GameCharacter from '../GameCharacter'

/**
 * @description - collection of games
 */
@Entity()
export class GamesResponse extends GameCharacter {
  constructor(item: any) {
    super(item)
  }
}

export default GamesResponse
