// Autogenerated 2/25/2022 9:41:54 PM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'
import Inventory from '../Inventory'

/**
 * @description - inventory response
 */
@Entity()
export class InventoryResponse extends Inventory {
  constructor(item: any) {
    super(item)
  }
}

export default InventoryResponse
