// Autogenerated 2/19/2022 4:49:06 PM
import { Entity } from 'typeorm'
import ItemDamageType from '../ItemDamageType'

/**
 * @description - Item damaged
 */
@Entity()
export class ItemDamageResponse {
  constructor(item: any) {
    const { result } = item
    this.result = result
  }
  result: ItemDamageType
}

export default ItemDamageResponse
