// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY
import { Entity } from 'typeorm'
import ItemDamageType from '../ItemDamageType'

/**
 * @description - Item damaged
 */
@Entity()
export class ItemDamageResponse {
  constructor(item: any) {
    const { result } = item
    this.result = result
  }
  result: ItemDamageType
}

export default ItemDamageResponse
