// Autogenerated 2/19/2022 4:49:06 PM
import { Entity } from 'typeorm'

/**
 * @description - login response
 */
@Entity()
export class LoginResponse {
  constructor(item: any) {
    const { token, player } = item
    this.token = token
    this.player = player
  }
  token: string
  player: string
}

export default LoginResponse
