// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY
import { Entity } from 'typeorm'
import PlayerDetail from '../PlayerDetail'

/**
 * @description - player details
 */
@Entity()
export class PlayerDetailResponse extends PlayerDetail {
  constructor(item: any) {
    super(item)
  }
}

export default PlayerDetailResponse
