// Autogenerated 2/19/2022 4:02:06 PM
import { Entity } from 'typeorm'
import PlayerDetail from '../PlayerDetail'

/**
 * description - player details
 *
 */
@Entity()
export class PlayerDetailResponse extends PlayerDetail {
  constructor(item: any) {
    super(item)
  }
}

export default PlayerDetailResponse
