// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY
import { Entity } from 'typeorm'
import PublicPlayer from '../PublicPlayer'

/**
 * @description - a player
 */
@Entity()
export class PlayerResponse extends PublicPlayer {
  constructor(item: any) {
    super(item)
  }
}

export default PlayerResponse
