// Autogenerated 2/19/2022 4:02:06 PM
import { Entity } from 'typeorm'
import PublicPlayer from '../PublicPlayer'

/**
 * description - a player
 *
 */
@Entity()
export class PlayerResponse extends PublicPlayer {
  constructor(item: any) {
    super(item)
  }
}

export default PlayerResponse
