parameters:
  - name: gameId
    required: true
    in: path
    description: the gameId to add the battle to
    schema:
      type: string
post:
  summary: create a new battle
  description: creates a new battle, adding the player's character associated with /games/{gameId} to the battle
  tags:
    - battle
  security:
    - playerGameMember: []
  operationId: createBattle
  responses:
    201:
      $ref: '../responses/_index.yaml#/Location'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
get:
  summary: get battles
  tags:
    - game
  security:
    - playerGameMember: []
  operationId: getGameBattles
  responses:
    200:
      $ref: '../responses/_index.yaml#/GameBattles'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
