parameters:
  - name: characterId
    required: true
    in: path
    description: the characterId
    schema:
      type: string
get:
  summary: retrieve character
  description: retrieves the public character
  tags:
    - character
  security:
    - playerGameCharacter: []
  operationId: getCharacter
  responses:
    200:
      $ref: '../responses/_index.yaml#/Character'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
patch:
  summary: update character partial
  tags:
    - character
  security:
    - playerCharacterOwner: []
  operationId: updateCharacter
  requestBody:
    $ref: '../requests/_index.yaml#/UpdateCharacter'
  responses:
    204:
      $ref: '../responses/_index.yaml#/DeleteOrUpdate'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
delete:
  summary: remove a character
  description: deletes the character and its inventory
  tags:
    - character
  security:
    - playerCharacterOwner: []
  operationId: deleteCharacter
  responses:
    204:
      $ref: '../responses/_index.yaml#/DeleteOrUpdate'
    401:
      $ref: '../responses/_index.yaml#/Fail'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
