post:
  security: []
  summary: login
  description: login the player to the specified game, initiate a socket if successful
  tags:
    - player
  operationId: login
  requestBody:
    $ref: '../requests/_index.yaml#/Login'

  responses:
    200:
      $ref: '../responses/_index.yaml#/Login'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
