get:
  summary: get all available races
  tags:
    - lists
  operationId: getRaces
  responses:
    200:
      $ref: '../responses/_index.yaml#/Races'
    404:
      $ref: '../responses/_index.yaml#/Fail'
    500:
      $ref: '../responses/_index.yaml#/Fail'
