import * as express from 'express'
import * as respond from '../../utils/express'
import Skill from '../models/Skill'
import Race from '../models/Race'
import { getRepo } from '../../utils/db'

/**
 * get all available skills
 */
export async function getSkills(req: express.Request, res: express.Response): Promise<void> {
  try {
    const response = await getRepo('Skill', Skill).find()
    // 200: Success
    return respond.OK(res, response)
  } catch (err) {
    return respond.INTERNAL_SERVER_ERROR(res, 'Internal Server Error')
  }
}

/**
 * get all available races
 */
// Autogenerated 5/31/2022 4:11:35 PM
//   by GenerateServerControllers.
export async function getRaces(req: express.Request, res: express.Response): Promise<void> {
  try {
    /* process the request and produce a response */
    const response = await getRepo('Race', Race).find()
    // 200: Success
    return respond.OK(res, response)
  } catch (err) {
    return respond.INTERNAL_SERVER_ERROR(res, 'Internal Server Error')
  }
}
