// Autogenerated 2/19/2022 4:02:06 PM
import { Entity } from 'typeorm'

@Entity()
export class BattleDamageRequest {
  constructor(item: any) {
    const { creatures, characters, damageType, damageAmt } = item
    this.creatures = creatures
    this.characters = characters
    this.damageType = damageType
    this.damageAmt = damageAmt
  }
  creatures: number[]
  characters: number[]
  damageType: number
  damageAmt: number
}

export default BattleDamageRequest
