// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY
import { Entity } from 'typeorm'

@Entity()
export class BattleDamageRequest {
  constructor(item: any) {
    const { creatures, characters, damageType, damageAmt } = item
    this.creatures = creatures
    this.characters = characters
    this.damageType = damageType
    this.damageAmt = damageAmt
  }
  creatures: number[]
  characters: number[]
  damageType: number
  damageAmt: number
}

export default BattleDamageRequest
