// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY
import { Entity } from 'typeorm'

@Entity()
export class CreateGameRequest {
  constructor(item: any) {
    const { name, maxPlayers } = item
    this.name = name
    this.maxPlayers = maxPlayers
  }
  name: string
  maxPlayers: number
}

export default CreateGameRequest
