// Autogenerated 2/20/2022 12:12:09 PM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'

@Entity()
export class InvitePlayerRequest {
  constructor(item: any) {
    const { email } = item
    this.email = email
  }
  email: string
}

export default InvitePlayerRequest
