// Autogenerated 2/16/2022 9:08:18 PM
import { Entity } from 'typeorm'

@Entity()
export class InvitePlayerRequest {
  constructor(item: any) {
    const { email } = item

    this.email = email
  }

  email: string
}

export default InvitePlayerRequest
