// Autogenerated 2/20/2022 9:48:42 AM
//   by GenerateServerModels.ts.  DO NOT MODIFY
import { Entity } from 'typeorm'

@Entity()
export class LoginRequest {
  constructor(item: any) {
    const { email, password } = item
    this.email = email
    this.password = password
  }
  email: string
  password: string
}

export default LoginRequest
