// Autogenerated 2/19/2022 4:49:06 PM
import { Entity } from 'typeorm'

@Entity()
export class MonsterRequest {
  constructor(item: any) {
    const { monsterId } = item
    this.monsterId = monsterId
  }
  monsterId: number
}

export default MonsterRequest
