// Autogenerated 2/20/2022 12:12:09 PM
//   by GenerateServerModels. DO NOT MODIFY
export class MonsterRequest {
  constructor(item: any) {
    const { monsterId } = item
    this.monsterId = monsterId
  }
  monsterId: number
}

export default MonsterRequest
