// Autogenerated 2/20/2022 12:12:09 PM
//   by GenerateServerModels. DO NOT MODIFY
import { Entity } from 'typeorm'

@Entity()
export class RenamePetRequest {
  constructor(item: any) {
    const { name } = item
    this.name = name
  }
  name: string
}

export default RenamePetRequest
