// Autogenerated 2/16/2022 9:08:18 PM
import { Entity } from 'typeorm'

@Entity()
export class RenamePetRequest {
  constructor(item: any) {
    const { name } = item

    this.name = name
  }

  name: string
}

export default RenamePetRequest
