// Autogenerated 2/16/2022 9:08:18 PM
import { Entity } from 'typeorm'

@Entity()
export class UpdateGameRequest {
  constructor(item: any) {
    const { name, maxPlayers } = item

    this.name = name
    this.maxPlayers = maxPlayers
  }

  name: string
  maxPlayers: number
}

export default UpdateGameRequest
