@baseUrl = http://localhost:3000
@rnd = {{$randomInt 1000 9999}}
@bearerAuth = {{login.response.body.token}}
@player1Name = {{register1.response.body.username}}
@player1Id = {{register1.response.body.id}}
@gameId = {{createGame.response.body.id}}

@inventoryId = {{createCharacter.response.body.inventory.id}}

### This file tests inventory/equipment functionality
### TODO: there are permissions issues for equipping/unequipping endpoints

### Create PLAYER 1
# @name register1
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "player{{rnd}}",
  "email": "player{{rnd}}@example.com",
  "password": "password"
}

### Login PLAYER 1
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{player1Name}}",
  "password": "password"
}

### Create a game
# @name createGame
POST {{baseUrl}}/games
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "test game {{rnd}}"
}

### Create a character in a game
# @name createCharacter
POST {{baseUrl}}/games/{{gameId}}/characters
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "test character {{rnd}}",
  "raceId": 1,
  "strength": {{$randomInt 1 4}},
  "dexterity": {{$randomInt 1 4}},
  "intelligence": {{$randomInt 1 4}},
  "skills": [
    { "id": 1, "level": 1 },
    { "id": 2, "level": 3 } ]
}

### Get character's inventory
GET {{baseUrl}}/inventory/{{inventoryId}}
Authorization: Bearer {{bearerAuth}}

### Get a random item
POST {{baseUrl}}/inventory/{{inventoryId}}/random
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "itemType": "armor",
  "level": 1
}

### Drop an item
PUT {{baseUrl}}/inventory/4/drop/jewelry/12
Authorization: Bearer {{bearerAuth}}

### Equip an item
PUT {{baseUrl}}/inventory/1/equip/armor/1
Authorization: Bearer {{bearerAuth}}

### Unequip an item
PUT {{baseUrl}}/inventory/1/unequip/weapon/2
Authorization: Bearer {{bearerAuth}}

