export const ConditionSeed = [
  {
    id: 1,
    name: `Lesser Poison`,
    actionReplace: ``,
    duration: 8,
    damage: `5-7`,
    delay: 2,
    cooldown: 3,
    removeOnHit: false,
    allowMultiple: false,
    damageType: 6
  },
  {
    id: 2,
    name: `Poison`,
    actionReplace: ``,
    duration: 16,
    damage: `7-11`,
    delay: 2,
    cooldown: 3,
    overrides: [1],
    removeOnHit: false,
    allowMultiple: false,
    damageType: 6
  },
  {
    id: 3,
    name: `Greater Poison`,
    actionReplace: ``,
    duration: 16,
    damage: `9-15`,
    delay: 1,
    cooldown: 2,
    overrides: [1, 2],
    removeOnHit: false,
    allowMultiple: false,
    damageType: 6
  },
  {
    id: 4,
    name: `Deadly Poison`,
    actionReplace: ``,
    duration: 24,
    damage: `13-27`,
    delay: 2,
    cooldown: 2,
    overrides: [1, 2, 3],
    removeOnHit: false,
    allowMultiple: false,
    damageType: 6
  },
  {
    id: 5,
    name: `Lethal Poison`,
    actionReplace: ``,
    duration: 32,
    damage: `21-33`,
    delay: 1,
    cooldown: 2,
    overrides: [1, 2, 3, 4],
    removeOnHit: false,
    allowMultiple: false,
    damageType: 6
  },
  {
    id: 6,
    name: `Cursed`,
    actionReplace: ``,
    duration: 0,
    damage: ``,
    delay: 0,
    cooldown: 0,
    removeOnHit: true,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 7,
    name: `Paralyzed`,
    actionReplace: `Paralyzed`,
    duration: 4,
    damage: ``,
    delay: 0,
    cooldown: 0,
    overrides: [17, 18],
    removeOnHit: true,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 8,
    name: `Mindblast`,
    actionReplace: ``,
    duration: 0,
    damage: `39-42`,
    delay: 3,
    cooldown: 0,
    removeOnHit: false,
    allowMultiple: true,
    damageType: 3
  },
  {
    id: 9,
    name: `Explosion`,
    actionReplace: ``,
    duration: 0,
    damage: `51-56`,
    delay: 4,
    cooldown: 0,
    removeOnHit: false,
    allowMultiple: true,
    damageType: 2
  },
  {
    id: 10,
    name: `Discorded`,
    actionReplace: ``,
    duration: 24,
    damage: ``,
    delay: 0,
    cooldown: 0,
    removeOnHit: false,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 11,
    name: `Peaced`,
    actionReplace: `Peaced`,
    duration: 12,
    damage: ``,
    delay: 0,
    cooldown: 0,
    overrides: [10, 12],
    removeOnHit: true,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 12,
    name: `Provoked`,
    actionReplace: ``,
    duration: 12,
    damage: ``,
    delay: 0,
    cooldown: 0,
    removeOnHit: false,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 13,
    name: `Corpseskin`,
    actionReplace: ``,
    duration: 16,
    damage: ``,
    delay: 0,
    cooldown: 0,
    removeOnHit: false,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 14,
    name: `Hidden`,
    actionReplace: ``,
    duration: 0,
    damage: ``,
    delay: 0,
    cooldown: 0,
    removeOnHit: false,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 15,
    name: `Mortal Strike`,
    actionReplace: `Mortal Strike`,
    duration: 5,
    damage: ``,
    delay: 0,
    cooldown: 0,
    removeOnHit: false,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 16,
    name: `Bleed`,
    actionReplace: ``,
    duration: 5,
    damage: `6`,
    delay: 0,
    cooldown: 1,
    removeOnHit: false,
    allowMultiple: false,
    damageType: 6
  },
  {
    id: 17,
    name: `Nerve Strike`,
    actionReplace: `Paralyzed`,
    duration: 2,
    damage: ``,
    delay: 0,
    cooldown: 0,
    overrides: [7, 18],
    removeOnHit: true,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 18,
    name: `Paralyze Blow`,
    actionReplace: `Paralyzed`,
    duration: 3,
    damage: ``,
    delay: 0,
    cooldown: 0,
    overrides: [7, 17],
    removeOnHit: true,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 19,
    name: `Armor Corruption`,
    actionReplace: ``,
    duration: 5,
    damage: ``,
    delay: 0,
    cooldown: 0,
    removeOnHit: false,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 20,
    name: `Attunement`,
    actionReplace: ``,
    duration: -1,
    damage: ``,
    delay: 0,
    cooldown: 0,
    removeOnHit: false,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 21,
    name: `Corruption`,
    actionReplace: ``,
    duration: 5,
    damage: ``,
    delay: 0,
    cooldown: 0,
    removeOnHit: false,
    allowMultiple: false,
    damageType: null
  },
  {
    id: 22,
    name: `Pack Leader`,
    actionReplace: ``,
    duration: -1,
    damage: ``,
    delay: 0,
    cooldown: 0,
    removeOnHit: false,
    allowMultiple: false,
    damageType: null
  }
];
