export const SkillSeed = [
  { id: 1, name: `Alchemy`, spellbook: true },
  { id: 2, name: `Anatomy`, spellbook: false },
  { id: 3, name: `Animal Lore`, spellbook: false },
  { id: 4, name: `Animal Taming`, spellbook: false },
  { id: 5, name: `Archery`, spellbook: false },
  { id: 6, name: `Arms Lore`, spellbook: false },
  { id: 7, name: `Blacksmithing`, spellbook: false },
  { id: 8, name: `Woodcrafting`, spellbook: false },
  { id: 9, name: `Bushido`, spellbook: true },
  { id: 10, name: `Cartography`, spellbook: false },
  { id: 11, name: `Chivalry`, spellbook: true },
  { id: 12, name: `Cooking`, spellbook: false },
  { id: 13, name: `Perception`, spellbook: false },
  { id: 14, name: `Discordence`, spellbook: false },
  { id: 15, name: `Evaluate Intelligence`, spellbook: true },
  { id: 16, name: `Fencing`, spellbook: false },
  { id: 17, name: `Fishing`, spellbook: false },
  { id: 18, name: `Focus`, spellbook: false },
  { id: 19, name: `Camping`, spellbook: false },
  { id: 20, name: `Healing`, spellbook: false },
  { id: 21, name: `Hiding`, spellbook: false },
  { id: 22, name: `Imbuing`, spellbook: false },
  { id: 23, name: `Inscription`, spellbook: true },
  { id: 24, name: `Lumberjacking`, spellbook: false },
  { id: 25, name: `Mace Fighting`, spellbook: false },
  { id: 26, name: `Magery`, spellbook: false },
  { id: 27, name: `Meditation`, spellbook: true },
  { id: 28, name: `Mining`, spellbook: false },
  { id: 29, name: `Necromancy`, spellbook: true },
  { id: 30, name: `Ninjitsu`, spellbook: true },
  { id: 31, name: `Parry`, spellbook: false },
  { id: 32, name: `Peacemaking`, spellbook: false },
  { id: 33, name: `Poisoning`, spellbook: false },
  { id: 34, name: `Provocation`, spellbook: false },
  { id: 35, name: `Spell Resist`, spellbook: true },
  { id: 36, name: `Snooping`, spellbook: false },
  { id: 37, name: `Spirit Speak`, spellbook: false },
  { id: 38, name: `Stealing`, spellbook: false },
  { id: 39, name: `Stealth`, spellbook: false },
  { id: 40, name: `Swordsmanship`, spellbook: false },
  { id: 41, name: `Tactics`, spellbook: false },
  { id: 42, name: `Throwing`, spellbook: false },
  { id: 43, name: `Tracking`, spellbook: false },
  { id: 44, name: `Veterinary`, spellbook: false },
  { id: 45, name: `Wrestling`, spellbook: false },
  { id: 46, name: `Spellweaving`, spellbook: true },
  { id: 47, name: `Mysticism`, spellbook: true }
]
