export const SlayerTypeSeed = [
  { id: 1, name: `Dragon Slayer` },
  { id: 2, name: `Repond (Super Slayer)` },
  { id: 3, name: `Ogre Slayer` },
  { id: 4, name: `Orc Slayer` },
  { id: 5, name: `Troll Slayer` },
  { id: 6, name: `Undead (Super Slayer)` },
  { id: 7, name: `Elemental (Super Slayer)` },
  { id: 8, name: `Air Elemental Slayer` },
  { id: 9, name: `Blood Elemental Slayer` },
  { id: 10, name: `Earth Elemental Slayer` },
  { id: 11, name: `Poison Elemental Slayer` },
  { id: 12, name: `Water Elemental Slayer` },
  { id: 13, name: `Snow Elemental Slayer` },
  { id: 14, name: `Demon (Super Slayer)` },
  { id: 15, name: `Gargoyle Slayer` },
  { id: 16, name: `Fey (Super Slayer)` },
  { id: 17, name: `Arachnid (Super Slayer)` },
  { id: 18, name: `Fire Elemental Slayer` },
  { id: 19, name: `Terathan Slayer` },
  { id: 20, name: `Scorpion Slayer` },
  { id: 21, name: `Spider Slayer` },
  { id: 22, name: `Reptile (Super Slayer)` }
];
