export const WeaponSeed = [
  {
    id: 1,
    name: `Assassin Spike`,
    damage: `10-12`,
    range: 0,
    speed: 2,
    strength: 1,
    hand: 1,
    skill: 1,
    primaryMove: 13,
    secondaryMove: 21,
    material: 1
  },
  {
    id: 2,
    name: `Dagger`,
    damage: `10-12`,
    range: 0,
    speed: 2,
    strength: 1,
    hand: 1,
    skill: 1,
    primaryMove: 13,
    secondaryMove: 21,
    material: 1
  },
  {
    id: 3,
    name: `Kryss`,
    damage: `10-12`,
    range: 0,
    speed: 2,
    strength: 1,
    hand: 1,
    skill: 1,
    primaryMove: 1,
    secondaryMove: 13,
    material: 1
  },
  {
    id: 4,
    name: `Short Spear`,
    damage: `10-13`,
    range: 0,
    speed: 2,
    strength: 2,
    hand: 2,
    skill: 1,
    primaryMove: 21,
    secondaryMove: 14,
    material: 1
  },
  {
    id: 5,
    name: `Club`,
    damage: `10-14`,
    range: 0,
    speed: 2,
    strength: 1,
    hand: 1,
    skill: 2,
    primaryMove: 1,
    secondaryMove: 2,
    material: 1
  },
  {
    id: 6,
    name: `War Fork`,
    damage: `10-14`,
    range: 0,
    speed: 4,
    strength: 2,
    hand: 1,
    skill: 1,
    primaryMove: 3,
    secondaryMove: 6,
    material: 1
  },
  {
    id: 7,
    name: `Cleaver`,
    damage: `11-13`,
    range: 0,
    speed: 4,
    strength: 1,
    hand: 1,
    skill: 3,
    primaryMove: 3,
    secondaryMove: 13,
    material: 1
  },
  {
    id: 8,
    name: `Cutlass`,
    damage: `11-13`,
    range: 0,
    speed: 4,
    strength: 1,
    hand: 1,
    skill: 3,
    primaryMove: 3,
    secondaryMove: 21,
    material: 1
  },
  {
    id: 9,
    name: `Katana`,
    damage: `11-13`,
    range: 0,
    speed: 4,
    strength: 1,
    hand: 1,
    skill: 3,
    primaryMove: 9,
    secondaryMove: 1,
    material: 1
  },
  {
    id: 10,
    name: `Wakizashi`,
    damage: `11-13`,
    range: 0,
    speed: 4,
    strength: 1,
    hand: 1,
    skill: 3,
    primaryMove: 12,
    secondaryMove: 9,
    material: 1
  },
  {
    id: 11,
    name: `Crescent Blade`,
    damage: `11-14`,
    range: 0,
    speed: 4,
    strength: 3,
    hand: 1,
    skill: 3,
    primaryMove: 9,
    secondaryMove: 14,
    material: 1
  },
  {
    id: 12,
    name: `Quarter Staff`,
    damage: `11-14`,
    range: 0,
    speed: 3,
    strength: 2,
    hand: 2,
    skill: 2,
    primaryMove: 9,
    secondaryMove: 5,
    material: 2
  },
  {
    id: 13,
    name: `Mace`,
    damage: `11-15`,
    range: 0,
    speed: 4,
    strength: 2,
    hand: 1,
    skill: 2,
    primaryMove: 5,
    secondaryMove: 6,
    material: 1
  },
  {
    id: 14,
    name: `Wand`,
    damage: `11-15`,
    range: 0,
    speed: 4,
    strength: 1,
    hand: 1,
    skill: 2,
    primaryMove: 7,
    secondaryMove: 6,
    material: 1
  },
  {
    id: 15,
    name: `Leafblade`,
    damage: `11-15`,
    range: 0,
    speed: 4,
    strength: 1,
    hand: 1,
    skill: 3,
    primaryMove: 10,
    secondaryMove: 1,
    material: 1
  },
  {
    id: 16,
    name: `Repeating Crossbow`,
    damage: `11-15`,
    range: 7,
    speed: 4,
    strength: 2,
    hand: 2,
    skill: 4,
    primaryMove: 8,
    secondaryMove: 15,
    material: 2
  },
  {
    id: 17,
    name: `Double Bladed Staff`,
    damage: `12-13`,
    range: 0,
    speed: 3,
    strength: 2,
    hand: 2,
    skill: 2,
    primaryMove: 9,
    secondaryMove: 13,
    material: 1
  },
  {
    id: 18,
    name: `Tetsubo`,
    damage: `12-15`,
    range: 0,
    speed: 4,
    strength: 2,
    hand: 1,
    skill: 2,
    primaryMove: 4,
    secondaryMove: 12,
    material: 1
  },
  {
    id: 19,
    name: `Pitchfork`,
    damage: `13-14`,
    range: 0,
    speed: 4,
    strength: 2,
    hand: 2,
    skill: 1,
    primaryMove: 3,
    secondaryMove: 7,
    material: 1
  },
  {
    id: 20,
    name: `Bone Harvester`,
    damage: `13-15`,
    range: 0,
    speed: 5,
    strength: 1,
    hand: 1,
    skill: 3,
    primaryMove: 18,
    secondaryMove: 14,
    material: 1
  },
  {
    id: 21,
    name: `Pickaxe`,
    damage: `13-15`,
    range: 0,
    speed: 5,
    strength: 2,
    hand: 1,
    skill: 1,
    primaryMove: 9,
    secondaryMove: 6,
    material: 1
  },
  {
    id: 22,
    name: `Scimitar`,
    damage: `13-15`,
    range: 0,
    speed: 5,
    strength: 1,
    hand: 1,
    skill: 3,
    primaryMove: 9,
    secondaryMove: 18,
    material: 1
  },
  {
    id: 23,
    name: `Daisho`,
    damage: `13-15`,
    range: 0,
    speed: 4,
    strength: 2,
    hand: 2,
    skill: 3,
    primaryMove: 10,
    secondaryMove: 9,
    material: 1
  },
  {
    id: 24,
    name: `Hatchet`,
    damage: `13-15`,
    range: 0,
    speed: 4,
    strength: 1,
    hand: 1,
    skill: 3,
    primaryMove: 1,
    secondaryMove: 6,
    material: 1
  },
  {
    id: 25,
    name: `Spear`,
    damage: `13-15`,
    range: 0,
    speed: 4,
    strength: 2,
    hand: 2,
    skill: 1,
    primaryMove: 1,
    secondaryMove: 18,
    material: 1
  },
  {
    id: 26,
    name: `Black Staff`,
    damage: `13-16`,
    range: 0,
    speed: 4,
    strength: 2,
    hand: 2,
    skill: 2,
    primaryMove: 22,
    secondaryMove: 18,
    material: 2
  },
  {
    id: 27,
    name: `Shepherd Crook`,
    damage: `13-16`,
    range: 0,
    speed: 4,
    strength: 1,
    hand: 2,
    skill: 2,
    primaryMove: 4,
    secondaryMove: 6,
    material: 2
  },
  {
    id: 28,
    name: `Diamond Mace`,
    damage: `13-17`,
    range: 0,
    speed: 5,
    strength: 2,
    hand: 1,
    skill: 2,
    primaryMove: 5,
    secondaryMove: 4,
    material: 1
  },
  {
    id: 29,
    name: `Sledge Hammer`,
    damage: `13-17`,
    range: 0,
    speed: 5,
    strength: 2,
    hand: 1,
    skill: 2,
    primaryMove: 4,
    secondaryMove: 21,
    material: 1
  },
  {
    id: 30,
    name: `Smith Hammer`,
    damage: `13-17`,
    range: 0,
    speed: 5,
    strength: 2,
    hand: 1,
    skill: 2,
    primaryMove: 4,
    secondaryMove: 21,
    material: 1
  },
  {
    id: 31,
    name: `War Axe`,
    damage: `13-17`,
    range: 0,
    speed: 5,
    strength: 2,
    hand: 1,
    skill: 2,
    primaryMove: 1,
    secondaryMove: 3,
    material: 1
  },
  {
    id: 32,
    name: `Yumi`,
    damage: `13-17`,
    range: 10,
    speed: 5,
    strength: 2,
    hand: 2,
    skill: 4,
    primaryMove: 2,
    secondaryMove: 8,
    material: 2
  },
  {
    id: 33,
    name: `Cyclone`,
    damage: `13-17`,
    range: 3,
    speed: 5,
    strength: 2,
    hand: 1,
    skill: 5,
    primaryMove: 15,
    secondaryMove: 7,
    material: 1
  },
  {
    id: 34,
    name: `Broadsword`,
    damage: `14-16`,
    range: 0,
    speed: 5,
    strength: 2,
    hand: 1,
    skill: 3,
    primaryMove: 4,
    secondaryMove: 1,
    material: 1
  },
  {
    id: 35,
    name: `Axe`,
    damage: `14-16`,
    range: 0,
    speed: 5,
    strength: 2,
    hand: 2,
    skill: 3,
    primaryMove: 4,
    secondaryMove: 7,
    material: 1
  },
  {
    id: 36,
    name: `Bladed Staff`,
    damage: `14-16`,
    range: 0,
    speed: 5,
    strength: 2,
    hand: 2,
    skill: 3,
    primaryMove: 1,
    secondaryMove: 7,
    material: 1
  },
  {
    id: 37,
    name: `Pike`,
    damage: `14-16`,
    range: 0,
    speed: 5,
    strength: 2,
    hand: 2,
    skill: 1,
    primaryMove: 18,
    secondaryMove: 13,
    material: 1
  },
  {
    id: 38,
    name: `Maul`,
    damage: `14-18`,
    range: 0,
    speed: 6,
    strength: 2,
    hand: 1,
    skill: 2,
    primaryMove: 9,
    secondaryMove: 5,
    material: 1
  },
  {
    id: 39,
    name: `Scepter`,
    damage: `14-18`,
    range: 0,
    speed: 6,
    strength: 2,
    hand: 1,
    skill: 2,
    primaryMove: 4,
    secondaryMove: 14,
    material: 1
  },
  {
    id: 40,
    name: `Longsword`,
    damage: `15-16`,
    range: 0,
    speed: 6,
    strength: 2,
    hand: 1,
    skill: 3,
    primaryMove: 1,
    secondaryMove: 5,
    material: 1
  },
  {
    id: 41,
    name: `Viking Sword`,
    damage: `15-17`,
    range: 0,
    speed: 6,
    strength: 2,
    hand: 1,
    skill: 3,
    primaryMove: 4,
    secondaryMove: 18,
    material: 1
  },
  {
    id: 42,
    name: `Battle Axe`,
    damage: `15-17`,
    range: 0,
    speed: 6,
    strength: 2,
    hand: 2,
    skill: 3,
    primaryMove: 3,
    secondaryMove: 5,
    material: 1
  },
  {
    id: 43,
    name: `Double Axe`,
    damage: `15-17`,
    range: 0,
    speed: 5,
    strength: 2,
    hand: 2,
    skill: 3,
    primaryMove: 9,
    secondaryMove: 22,
    material: 1
  },
  {
    id: 44,
    name: `Executioner Axe`,
    damage: `15-17`,
    range: 0,
    speed: 5,
    strength: 2,
    hand: 2,
    skill: 3,
    primaryMove: 3,
    secondaryMove: 14,
    material: 1
  },
  {
    id: 45,
    name: `Hammer Pick`,
    damage: `15-17`,
    range: 0,
    speed: 5,
    strength: 2,
    hand: 1,
    skill: 2,
    primaryMove: 1,
    secondaryMove: 14,
    material: 1
  },
  {
    id: 46,
    name: `Scythe`,
    damage: `15-18`,
    range: 0,
    speed: 6,
    strength: 2,
    hand: 2,
    skill: 3,
    primaryMove: 3,
    secondaryMove: 18,
    material: 1
  },
  {
    id: 47,
    name: `War Mace`,
    damage: `15-19`,
    range: 0,
    speed: 6,
    strength: 4,
    hand: 1,
    skill: 2,
    primaryMove: 4,
    secondaryMove: 14,
    material: 1
  },
  {
    id: 48,
    name: `Bow`,
    damage: `15-19`,
    range: 10,
    speed: 7,
    strength: 2,
    hand: 2,
    skill: 4,
    primaryMove: 18,
    secondaryMove: 14,
    material: 2
  },
  {
    id: 49,
    name: `Elven Longbow`,
    damage: `15-19`,
    range: 10,
    speed: 6,
    strength: 2,
    hand: 2,
    skill: 4,
    primaryMove: 11,
    secondaryMove: 20,
    material: 2
  },
  {
    id: 50,
    name: `Large Battle Axe`,
    damage: `16-17`,
    range: 0,
    speed: 6,
    strength: 4,
    hand: 2,
    skill: 3,
    primaryMove: 22,
    secondaryMove: 3,
    material: 1
  },
  {
    id: 51,
    name: `Two Handed Axe`,
    damage: `16-17`,
    range: 0,
    speed: 6,
    strength: 2,
    hand: 2,
    skill: 3,
    primaryMove: 9,
    secondaryMove: 21,
    material: 1
  },
  {
    id: 52,
    name: `No-Dachi`,
    damage: `16-18`,
    range: 0,
    speed: 6,
    strength: 2,
    hand: 2,
    skill: 3,
    primaryMove: 19,
    secondaryMove: 7,
    material: 1
  },
  {
    id: 53,
    name: `Composoite Bow`,
    damage: `16-20`,
    range: 10,
    speed: 7,
    strength: 2,
    hand: 2,
    skill: 4,
    primaryMove: 1,
    secondaryMove: 15,
    material: 2
  },
  {
    id: 54,
    name: `Bardiche`,
    damage: `17-18`,
    range: 0,
    speed: 6,
    strength: 2,
    hand: 2,
    skill: 3,
    primaryMove: 18,
    secondaryMove: 7,
    material: 1
  },
  {
    id: 55,
    name: `War Hammer`,
    damage: `17-20`,
    range: 0,
    speed: 6,
    strength: 4,
    hand: 2,
    skill: 2,
    primaryMove: 22,
    secondaryMove: 4,
    material: 1
  },
  {
    id: 56,
    name: `Halbard`,
    damage: `18-19`,
    range: 0,
    speed: 7,
    strength: 4,
    hand: 2,
    skill: 3,
    primaryMove: 22,
    secondaryMove: 5,
    material: 1
  },
  {
    id: 57,
    name: `Ornate Axe`,
    damage: `18-20`,
    range: 0,
    speed: 6,
    strength: 2,
    hand: 2,
    skill: 3,
    primaryMove: 6,
    secondaryMove: 4,
    material: 1
  },
  {
    id: 58,
    name: `Lance`,
    damage: `18-22`,
    range: 0,
    speed: 7,
    strength: 4,
    hand: 2,
    skill: 1,
    primaryMove: 7,
    secondaryMove: 5,
    material: 1
  },
  {
    id: 59,
    name: `Crossbow`,
    damage: `18-22`,
    range: 0,
    speed: 6,
    strength: 2,
    hand: 2,
    skill: 4,
    primaryMove: 5,
    secondaryMove: 14,
    material: 2
  },
  {
    id: 60,
    name: `Soul Glaive`,
    damage: `18-22`,
    range: 5,
    speed: 7,
    strength: 3,
    hand: 1,
    skill: 5,
    primaryMove: 1,
    secondaryMove: 14,
    material: 1
  },
  {
    id: 61,
    name: `Paladin Sword`,
    damage: `20-24`,
    range: 0,
    speed: 6,
    strength: 4,
    hand: 2,
    skill: 3,
    primaryMove: 22,
    secondaryMove: 6,
    material: 1
  },
  {
    id: 62,
    name: `Paladin Sword`,
    damage: `20-24`,
    range: 0,
    speed: 6,
    strength: 4,
    hand: 2,
    skill: 3,
    primaryMove: 22,
    secondaryMove: 6,
    material: 1
  },
  {
    id: 63,
    name: `Heavy Crossbow`,
    damage: `20-24`,
    range: 8,
    speed: 8,
    strength: 4,
    hand: 2,
    skill: 4,
    primaryMove: 15,
    secondaryMove: 7,
    material: 2
  },
  {
    id: 64,
    name: `Boomerang`,
    damage: `8-12`,
    range: 0,
    speed: 4,
    strength: 1,
    hand: 1,
    skill: 5,
    primaryMove: 16,
    secondaryMove: 5,
    material: 2
  },
  {
    id: 65,
    name: `Bokuto`,
    damage: `9-11`,
    range: 0,
    speed: 2,
    strength: 1,
    hand: 1,
    skill: 3,
    primaryMove: 10,
    secondaryMove: 17,
    material: 2
  },
  {
    id: 66,
    name: `Butcher Knife`,
    damage: `9-11`,
    range: 0,
    speed: 3,
    strength: 1,
    hand: 1,
    skill: 3,
    primaryMove: 13,
    secondaryMove: 6,
    material: 1
  },
  {
    id: 67,
    name: `Skinning Knife`,
    damage: `9-11`,
    range: 0,
    speed: 3,
    strength: 1,
    hand: 1,
    skill: 3,
    primaryMove: 21,
    secondaryMove: 6,
    material: 1
  }
];
