export const WeaponAttributeSeed = [
  {
    id: 1,
    name: `Defence Chance Increase`,
    value: `1-15`,
    hand: 0,
    skill: null
  },
  { id: 2, name: `Antique`, value: ``, hand: 0, skill: null },
  { id: 3, name: `Slayer`, value: ``, hand: 0, skill: null },
  { id: 4, name: `Spell Channeling`, value: ``, hand: 0, skill: null },
  { id: 5, name: `Faster Casting 1`, value: ``, hand: 0, skill: null },
  { id: 6, name: `Cursed`, value: ``, hand: 0, skill: null },
  { id: 7, name: `Hit Chance Increase`, value: `1-15`, hand: 0, skill: null },
  { id: 8, name: `Damage Increase`, value: `1-50`, hand: 0, skill: null },
  { id: 9, name: `Hit Chance Increase`, value: `1-15`, hand: 0, skill: null },
  { id: 10, name: `Energy Reduction`, value: `1-15`, hand: 0, skill: null },
  { id: 11, name: `Fire Reduction`, value: `1-15`, hand: 0, skill: null },
  { id: 12, name: `Physical Reduction`, value: `1-15`, hand: 0, skill: null },
  { id: 13, name: `Poison Reduction`, value: `1-15`, hand: 0, skill: null },
  { id: 14, name: `Hit Cold Area`, value: `1-50`, hand: 0, skill: null },
  { id: 15, name: `Hit Curse`, value: `1-50`, hand: 0, skill: null },
  { id: 16, name: `Hit Dispel`, value: `1-50`, hand: 0, skill: null },
  { id: 17, name: `Hit Energy Area`, value: `1-50`, hand: 0, skill: null },
  { id: 18, name: `Hit Fatigue`, value: `1-50`, hand: 0, skill: null },
  { id: 19, name: `Cold Reduction`, value: `1-15`, hand: 0, skill: null },
  { id: 20, name: `Hit Fire Area`, value: `1-50`, hand: 0, skill: null },
  { id: 21, name: `Hit Fireball`, value: `1-50`, hand: 0, skill: null },
  { id: 22, name: `Hit Harm`, value: `1-50`, hand: 0, skill: null },
  { id: 23, name: `Hit Life Leech`, value: `1-50`, hand: 0, skill: null },
  { id: 24, name: `Hit Lightning`, value: `1-50`, hand: 0, skill: null },
  { id: 25, name: `Hit Lower Attack`, value: `1-50`, hand: 0, skill: null },
  { id: 26, name: `Hit Lower Defense`, value: `1-50`, hand: 0, skill: null },
  { id: 27, name: `Hit Magic Arrow`, value: `1-50`, hand: 0, skill: null },
  { id: 28, name: `Hit Mana Drain`, value: `1-50`, hand: 0, skill: null },
  { id: 29, name: `Hit Mana Leech`, value: `1-50`, hand: 0, skill: null },
  { id: 30, name: `Hit Physical Area`, value: `1-50`, hand: 0, skill: null },
  { id: 31, name: `Hit Poison Area`, value: `1-50`, hand: 0, skill: null },
  { id: 32, name: `Hit Stamina Leech`, value: `1-50`, hand: 0, skill: null },
  { id: 33, name: `Hit Life Leech`, value: `1-50`, hand: 0, skill: null },
  { id: 34, name: `Hit Lightning`, value: `1-50`, hand: 0, skill: null },
  { id: 35, name: `Mage Weapon`, value: ``, hand: 0, skill: null },
  { id: 36, name: `Massive`, value: ``, hand: 0, skill: null },
  { id: 37, name: `Swing Speed Inc 1`, value: ``, hand: 0, skill: null },
  { id: 38, name: `Unwieldy`, value: ``, hand: 0, skill: null },
  { id: 39, name: `Use Best Weapon Skill`, value: ``, hand: 0, skill: null },
  { id: 40, name: `Brittle`, value: ``, hand: 0, skill: null },
  { id: 41, name: `Balanced`, value: ``, hand: 2, skill: null },
  { id: 42, name: `Velocity`, value: ``, hand: 0, skill: 4 }
]
