description: Create character request
required: true
content:
  application/json:
    schema:
      type: object
      additionalProperties: false
      required:
        - name
        - strength
        - dexterity
        - intelligence
        - movement
      properties:
        name:
          type: string
        strength:
          type: number
        dexterity:
          type: number
        intelligence:
          type: number
        movement:
          type: number
