description: Create or Update character request
required: true
content:
  application/json:
    schema:
      type: object
      additionalProperties: false
      required:
        - name
        - maxHp
        - baseResist
        - inventorySize
      properties:
        name:
          type: string
        maxHp:
          type: number
        baseResist:
          type: number
        inventorySize:
          type: number
