description: Update game request
required: true
content:
  application/json:
    schema:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        maxPlayers:
          type: number
