description: login success
content:
  application/json:
    schema:
      type: object
      additionalProperties: false
      required:
        - token
        - player
      properties:
        token:
          type: string
        player:
          type: string
