description: Character details
type: object
allOf:
  - $ref: './_index.yaml#/PublicCharacter'
properties:
  player:
    type: string
  hp:
    type: number
  maxHp:
    type: number
  hpReplenish:
    type: number
  mana:
    type: number
  maxMana:
    type: number
  manaReplenish:
    type: number
  strength:
    type: number
  dexterity:
    type: number
  intelligence:
    type: number
  stamina:
    type: number
  maxStamina:
    type: number
  staminaReplenish:
    type: number
  hunger:
    type: number
  sleep:
    type: number
  movement:
    type: number
  hitChance:
    type: number
  defChance:
    type: number
  parry:
    type: number
  swingSpeed:
    type: number
  castSpeed:
    type: number
  healSpeed:
    type: number
  inventorySize:
    type: number
  resistPh:
    type: number
  resistF:
    type: number
  resistP:
    type: number
  resistC:
    type: number
  resistE:
    type: number
  inventory:
    $ref: './_index.yaml#/Inventory'
  skills:
    type: array
    items:
      $ref: './_index.yaml#/CharacterSkill'
