description: A race
type: object
properties:
  id:
    type: string
  name:
    type: string
  description:
    type: string
  skills:
    type: array
    items:
      $ref: '../schemas/_index.yaml#/CharacterSkill'
