@baseUrl = http://localhost:3000
@bearerAuth = {{login.response.body.token}}

### Create PLAYER 1
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "eric",
  "email": "eric@heimerman.org",
  "password": "eric"
}

### Create PLAYER 2
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "eric2",
  "email": "eric2@heimerman.org",
  "password": "eric"
}

### Login PLAYER 1
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "eric",
  "password": "eric"
}

### Login PLAYER 2
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "eric2",
  "password": "eric"
}

### Get all players
GET {{baseUrl}}/players
Authorization: Bearer {{bearerAuth}}

### update a player
PATCH {{baseUrl}}/players/1
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "email": "whatever@heimerman.org"
}

### delete a player
DELETE {{baseUrl}}/players/1
Authorization: Bearer {{bearerAuth}}

### Get a player
GET {{baseUrl}}/players/1
Authorization: Bearer {{bearerAuth}}

### Log out
# @name logout
GET {{baseUrl}}/auth/logout
Authorization: Bearer {{bearerAuth}}

### Create a game
POST {{baseUrl}}/games
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "test game"
}

### Get all games
GET {{baseUrl}}/games
Authorization: Bearer {{bearerAuth}}

### Get one game
GET {{baseUrl}}/games/1
Authorization: Bearer {{bearerAuth}}

### Update game name
PATCH {{baseUrl}}/games/1
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "RENAMED GAME 1"
}

### Delete a game
DELETE {{baseUrl}}/games/1
Authorization: Bearer {{bearerAuth}}

### Add player to a game
POST {{baseUrl}}/games/1/players/2
Authorization: Bearer {{bearerAuth}}

### Remove player from a game
DELETE {{baseUrl}}/games/1/players/2
Authorization: Bearer {{bearerAuth}}

### Create a character
POST {{baseUrl}}/games/1/characters
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "test character",
  "strength": 4,
  "dexterity": 1,
  "intelligence": 2
}

### Delete a character
DELETE {{baseUrl}}/characters/1
Authorization: Bearer {{bearerAuth}}

### Get all characters for a game
GET {{baseUrl}}/games/1/characters
Authorization: Bearer {{bearerAuth}}

### Get a character
GET {{baseUrl}}/characters/1
Authorization: Bearer {{bearerAuth}}

### Update a character
PATCH {{baseUrl}}/characters/1
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "test character renamed"
}

### Get all conditions
GET {{baseUrl}}/conditions
Authorization: Bearer {{bearerAuth}}

### Get all inventories
GET {{baseUrl}}/inventory
Authorization: Bearer {{bearerAuth}}

### Save a map
POST {{baseUrl}}/map
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

[{"tileIndex":0,"terrain":0},{"tileIndex":1,"terrain":0},{"tileIndex":2,"terrain":0},{"tileIndex":3,"terrain":0},{"tileIndex":4,"terrain":0},{"tileIndex":5,"terrain":0},{"tileIndex":6,"terrain":0},{"tileIndex":7,"terrain":0},{"tileIndex":8,"terrain":0},{"tileIndex":9,"terrain":0}]

### Get a map
GET {{baseUrl}}/map
Authorization: Bearer {{bearerAuth}}