@baseUrl = http://localhost:3000
@bearerAuth = {{login.response.body.access_token}}

### Create PLAYER 1
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "eric",
  "email": "eric@heimerman.org",
  "password": "eric"
}

### Create PLAYER 2
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "eric2",
  "email": "eric2@heimerman.org",
  "password": "eric"
}

### Login PLAYER 1
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "eric",
  "password": "eric"
}

### Login PLAYER 2
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "eric2",
  "password": "eric"
}

### Get all players
GET {{baseUrl}}/players
Authorization: Bearer {{bearerAuth}}

### Get a player
GET {{baseUrl}}/players/1
Authorization: Bearer {{bearerAuth}}

### Log out
# @name logout
GET {{baseUrl}}/auth/logout
Authorization: Bearer {{bearerAuth}}

### Create a game
POST {{baseUrl}}/games
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "test game"
}

### Get all games
GET {{baseUrl}}/games
Authorization: Bearer {{bearerAuth}}

### Get one game
GET {{baseUrl}}/games/6
Authorization: Bearer {{bearerAuth}}

### Update game name
PATCH {{baseUrl}}/games/4
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "RENAMED GAME 6"
}

### Delete a game
DELETE {{baseUrl}}/games/6
Authorization: Bearer {{bearerAuth}}

### Add player to a game
POST {{baseUrl}}/games/4/players/2
Authorization: Bearer {{bearerAuth}}

### Remove player from a game
DELETE {{baseUrl}}/games/4/players/2
Authorization: Bearer {{bearerAuth}}

### Create a character
POST {{baseUrl}}/games/1/characters
Authorization: Bearer {{bearerAuth}}
Content-Type: application/json

{
  "name": "test character",
  "strength": 3,
  "dexterity": 1,
  "intelligence": 2
}

### Delete a character
DELETE {{baseUrl}}/characters/3
Authorization: Bearer {{bearerAuth}}
