/**
 * @description generate a standard header
 * @param generatorName name of the file generating the file
 * @param allowModify should the resulting file be edited by hand after generating?
 * @returns
 */
export function buildStandardHeader(generatorName: string, allowModify = false) {
  const buildtime = new Date()
  const buildstring = `${buildtime.toLocaleDateString()} ${buildtime.toLocaleTimeString()}`
  return `// Autogenerated ${buildstring}\n//   by ${generatorName}.${allowModify ? '' : ' DO NOT MODIFY'}`
}
