description: Request failed
content:
  application/json:
    schema:
      type: object
      additionalProperties: false
      required:
        - success
        - error
      properties:
        success:
          type: boolean
        error:
          $ref: '../schemas/_index.yaml#/Error'
